New storage sell page
rsksmart/rif-marketplace-ui pull request #353
Opened 2020-09-08 14:30 UTC by farinalvaro

2020-09-11 11:58 UTC, AuHau commented on src/contracts/Storage.ts
> +    const message = [padRight(asciiToHex(peerId), 64)]
Unfortunately, this won't work.
"Messages" is a general concept in the Storage SC that allows passing information. As Rinke designed this, he defined that each message type is prefixed with one byte that defines what type of message it is. As you can see [here](https://github.com/rsksmart/rif-marketplace-storage#message) we currently have only one type and that is announcing PeerId type.
I originally was thinking about refactoring it into making the PeerId required for the Offer (see the [PR](https://github.com/rsksmart/rif-marketplace-storage/pull/105), but then we decided to not do it as it is not really mandatory from the SC point of view, but rather the system itself, so we gonna enforce that on Cache level...

So there are two problems here:
 - the message has to have `0x01` prefix
 - as the parameter is `byte32[]` and PeerId is usually 47 chars, you have to split the string into chunks. Btw. you should not really on the length 47 chars, make it generic solution.

For the splitting part you can see it working at [here](https://github.com/rsksmart/rif-storage-pinner/blob/63f2e8679a3e2900639f8fbbc9479a147ba35b80/test/utils.ts#L40), but... That is unfortunately not the full solution here (but can be used for encoding the IPFS hash, that is passed to the SC when you create new Agreement).

Problem is that when you call it as like this `const msg = encodeHash(peerId)` you get an array like `[first32bytes, second32bytes, ...]`, but then you should prefix the first element with the `0x01` which will make it overflow the `byte32` length. So there has to be "shifting" mechanism that moves the excess bytes into later elements, but I still have not got around to write this part, sooo maybe you will and I can steal it afterwards 😅 😇

2020-09-11 13:13 UTC, farinalvaro commented on src/contracts/Storage.ts
> +    const message = [padRight(asciiToHex(peerId), 64)]
Hey Adam, thanks for this valuable comment 🙂
We were discussing with @jurajpiar and will be working on the PeerId on a separated PR, so I would better keep sending an empty message for now.
As for the shifting mechanism, let's talk and tackle it on that new PR

2020-09-14 06:55 UTC, jurajpiar requested changes
Nice, just need to remove some smelly code .)

2020-09-14 06:55 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditablePlanItem.tsx
> +      <TooltipIconButton
I don't think this needs to be a function here.

2020-09-14 06:55 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditablePlanItem.tsx
> +          ),
Nesting ternary operators is not encouraged. They are harder to read (as you have to keep the previous parts in mind), harder to debug and is prone to errors (similar to switch/case or even nested ifs). We seem to have that rule overwritten to just a warning but we should still avoid it where possible.

2020-09-14 14:19 UTC, farinalvaro commented on src/components/organisms/storage/sell/EditablePlanItem.tsx
> +          ),
Thanks, good point

2020-09-14 14:25 UTC, farinalvaro commented on src/components/organisms/storage/sell/SellStepper.tsx
> +  finalAction: ReactElement
As it's a ReactElement, I followed your previous suggestion of renaming it to `endHandler`

2020-09-14 14:50 UTC, farinalvaro commented on src/context/Services/storage/listingReducer.ts
> +}
Done. Thanks

2020-09-14 14:50 UTC, farinalvaro commented on src/components/organisms/storage/sell/EditablePlanItem.tsx
> +      <TooltipIconButton
I think it just helps to avoid using the nested ternary operator as you suggested and also helps with the readability. Please, take a look at the new function without the ternary operator and let me know if you still think the same 🙂

2020-09-15 10:45 UTC, jurajpiar approved these changes
LGTM

2020-09-15 10:45 UTC, merged