Feature/edit sotrage offer
rsksmart/rif-marketplace-ui pull request #368
Opened 2020-09-22 19:20 UTC by farinalvaro

2020-09-23 13:00 UTC, julianmrodri commented on package.json
>      "@rsksmart/rif-marketplace-storage": "0.1.0-dev.1",
@nduchak I believe we need to bump this to `dev.2` in this PR right? I had to do it locally for the UI to take the new abi.

2020-09-23 13:01 UTC, nduchak commented on package.json
>      "@rsksmart/rif-marketplace-storage": "0.1.0-dev.1",
Yes, I forgot to bump version in my PR

2020-09-23 14:38 UTC, farinalvaro commented on package.json
>      "@rsksmart/rif-marketplace-storage": "0.1.0-dev.1",
Done

2020-09-29 18:51 UTC, farinalvaro commented on src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
> +})
This code is repeated in the sell page, I would like to restructure the `contracts` folder to add a `storage` folder with
- `interfaces.ts` containing `OfferContractData`
- `utils.ts` containing `transformOfferDataForContract` and some other functions like the one that encodes the `peerId`
- `contracts.ts` replacing the current `storage.ts`

Please, share your thoughts on this and if we agree I will create an issue and new PR :)

2020-09-29 18:51 UTC, farinalvaro commented on src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
> +  }
This is also repeated but temporal as we want to optimize the calls to the SC to only update what has been changed https://github.com/rsksmart/rif-marketplace-ui/issues/377

2020-09-29 19:36 UTC, nduchak commented on src/context/Market/storage/interfaces.ts
> +const ZeroAddress = '0x0000000000000000000000000000000000000000'
Actually, we already have this constant. Just need to export it ;)
https://github.com/rsksmart/rif-marketplace-ui/blob/master/src/context/Services/storage/interfaces.ts#L57

2020-09-30 05:27 UTC, julianmrodri submitted a review, later dismissed
LGTM

2020-10-01 15:35 UTC, nduchak commented on src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
> +})
Agree with you. This should be structured by services

2020-10-06 11:52 UTC, julianmrodri submitted a review, later dismissed
LGTM - We need to review those cases we discussed later.

2020-10-06 12:32 UTC, jurajpiar commented on src/components/molecules/CryptoPriceConverter.tsx
> +          value={price?.toString()}
price is a type of string

2020-10-06 12:38 UTC, jurajpiar commented on src/components/organisms/TransactionInProgressPanel.tsx
> +  onProcessingComplete = (): void => undefined, overlayed,
new line before overlayed

2020-10-06 12:40 UTC, jurajpiar commented on src/components/organisms/TransactionInProgressPanel.tsx
> +  return panelContent
Adapt the rest of the app, namely, `renderProgressOverlay` in `src/components/pages/storage/buy/StorageOffersCheckoutPage.tsx might need to change a bit.

2020-10-06 12:55 UTC, farinalvaro commented on src/components/molecules/CryptoPriceConverter.tsx
> +          value={price?.toString()}
Thanks for spotting this 👌

2020-10-06 13:03 UTC, farinalvaro commented on src/components/organisms/TransactionInProgressPanel.tsx
> +  return panelContent
I adapted this to the rest of the app but in the case of `StorageOffersCheckoutPage.tsx`, the overlay is covering also `TxCompletePageTemplate` and not only `TransactionInProgressPanel`. So I thought it would be better to do it in another refactor.

2020-10-06 13:03 UTC, jurajpiar commented on src/components/organisms/storage/sell/BillingPlan.tsx
> +  const fiatPriceDisplay = priceDisplay(Number(fiatPrice), 2)
So.... why doesn't it?
Also the fn seems to only work if the maxDecimal is not bigger than 8 so it may need changing anyway...

2020-10-06 13:08 UTC, jurajpiar commented on src/components/organisms/storage/sell/BillingPlansList.tsx
> +                  (a: StorageBillingPlan, b: StorageBillingPlan) => (PeriodInSeconds[a.period] - PeriodInSeconds[b.period]),
could be cleaner as
```
({period: a}, {period: b}) => (PeriodInSeconds[a] - PeriodInSeconds[b])
```

2020-10-06 13:09 UTC, farinalvaro commented on src/components/organisms/storage/sell/BillingPlan.tsx
> +  const fiatPriceDisplay = priceDisplay(Number(fiatPrice), 2)
Missed this one, thanks

2020-10-06 13:16 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +              allBillingPeriods.sort((a, b) => a - b).map(
put .map on new line

2020-10-06 13:17 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +                  const isDisabled = usedPeriodsPerCurrency[currency]?.includes(option) && option !== billingPlan?.period
.includes on new line please

2020-10-06 13:18 UTC, jurajpiar commented on src/components/organisms/storage/sell/GeneralFeatures.tsx
> +          disabled={!!originalOffer}
use Boolean(originalOffer)

2020-10-06 13:20 UTC, jurajpiar commented on src/components/pages/storage/StorageRoutes.tsx
> +              <Route exact path={ROUTES.STORAGE.MYOFFERS.EDIT.DONE} component={StorageEditOfferDone} />
pretty sure these lines are too long

2020-10-06 13:20 UTC, farinalvaro commented on src/components/organisms/storage/sell/GeneralFeatures.tsx
> +          disabled={!!originalOffer}
All over the app we are using this. Also, please submit all your comments in only one review

2020-10-06 13:21 UTC, farinalvaro commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +              allBillingPeriods.sort((a, b) => a - b).map(
This is working for our linter and doesn't add any value to the PR

2020-10-06 13:22 UTC, jurajpiar commented on src/components/organisms/TransactionInProgressPanel.tsx
> +  return panelContent
I doubt you'll get back to it, but be it what you will .]

2020-10-06 13:27 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +              allBillingPeriods.sort((a, b) => a - b).map(
it adds to readability

2020-10-06 13:29 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +              allBillingPeriods.sort((a, b) => a - b).map(
whenever chaining you should write each call on its own line, like you'd do with promises, right?

2020-10-06 13:30 UTC, jurajpiar commented on src/components/organisms/storage/sell/GeneralFeatures.tsx
> +          disabled={!!originalOffer}
yea I know but also we're increasingly using the TS way of doing this so might as well

2020-10-06 13:33 UTC, jurajpiar commented on src/context/Market/storage/interfaces.ts
> +const ZeroAddress = '0x0000000000000000000000000000000000000000'
this already exists in `src/context/Services/storage/interfaces.ts`. Also it shouldn't begin with uppercase.

2020-10-06 13:37 UTC, farinalvaro commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +                  const isDisabled = usedPeriodsPerCurrency[currency]?.includes(option) && option !== billingPlan?.period
Not possible because of `?`. Anyway I moved the `&&` to new line

2020-10-06 13:38 UTC, farinalvaro commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +              allBillingPeriods.sort((a, b) => a - b).map(
👍

2020-10-06 13:39 UTC, jurajpiar commented on src/utils/utils.ts
> +export const priceDisplay = (value: number | Big, maxDecimals = 8): string => value
use `value: BigSource` instead.

2020-10-06 13:41 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +                  const isDisabled = usedPeriodsPerCurrency[currency]?.includes(option) && option !== billingPlan?.period
same as https://github.com/rsksmart/rif-marketplace-ui/pull/368#discussion_r500276271

2020-10-06 13:42 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditableBillingPlan.tsx
> +                  const isDisabled = usedPeriodsPerCurrency[currency]?.includes(option) && option !== billingPlan?.period
ok

2020-10-06 13:43 UTC, farinalvaro commented on src/utils/utils.ts
> +export const priceDisplay = (value: number | Big, maxDecimals = 8): string => value
```
Property 'toFixed' does not exist on type 'BigSource'.
Property 'toFixed' does not exist on type 'string'.
```

2020-10-06 13:44 UTC, jurajpiar commented on src/utils/utils.ts
> +export const priceDisplay = (value: number | Big, maxDecimals = 8): string => value
fair enough

2020-10-06 13:45 UTC, jurajpiar submitted a review, later dismissed
Good to go, except for the failing linter

2020-10-06 13:47 UTC, farinalvaro commented on src/components/organisms/storage/sell/GeneralFeatures.tsx
> +          disabled={!!originalOffer}
Good point, changed it

2020-10-06 13:48 UTC, jurajpiar approved these changes

2020-10-06 13:51 UTC, jurajpiar requested changes
Actually one more thing.
Please, rebase on your own changes and squash commits that are not going to be useful in the master branch history.
Failing that would mean that squash merge should be preferred to a rebase.
That is, if you want to have a clean commit history.

2020-10-06 15:32 UTC, farinalvaro commented
@jurajpiar I just rebased what was reasonable to not mess a lot with the history.
I would prefer to have a commit with `refactor: cleans up code` than a commit with a thousand lines.
I think we should have an agreement on this and also discuss this kind of things outside of this PR.

2020-10-06 18:26 UTC, julianmrodri commented
This is ready to be merged IMO. i dont think its a wise strategy now to focus  a lot of time just for the commit history. Lets get this done so Alvaro can move to the Staking. Thanks!!

2020-10-06 18:31 UTC, jurajpiar approved these changes

2020-10-06 18:33 UTC, merged