feat:
rsksmart/rif-marketplace-ui pull request #423
Opened 2020-10-23 20:23 UTC by farinalvaro

- adds ability to fetch agreements by consumer or provider
- adds set filters action in reducer

2020-10-27 20:28 UTC, julianmrodri approved these changes
LGTM

2020-10-27 20:40 UTC, julianmrodri approved these changes
LGTM

2020-10-28 15:36 UTC, jurajpiar requested changes
Nice job! Just remove the unnecessary check in agreements _fetch, and in the Context make the filters object optional, which should replace the account check in the fetching useEffect.

2020-10-28 15:51 UTC, farinalvaro commented on src/components/organisms/storage/myoffers/ExpandableOffer.tsx
> +    dispatch: agreementsDispatch,
well, to be honest I just found it easier to read when using it 😅

2020-10-28 16:10 UTC, farinalvaro commented on src/context/Services/storage/agreements/Context.tsx
> +    provider: undefined,
fixed, thanks

2020-10-28 16:10 UTC, farinalvaro commented on src/context/Services/storage/agreements/Context.tsx
> +  }, [isInitialised, api, account, appDispatch, filters])
fixed, thanks

2020-10-28 16:16 UTC, jurajpiar approved these changes
Sweet as

2020-10-28 16:19 UTC, merged