Feat/multi currency for contracts
rsksmart/rif-marketplace-ui pull request #450
Opened 2020-11-04 14:10 UTC by nduchak

2020-11-06 14:15 UTC, farinalvaro reviewed
Great job 👏 . I just left a few comments.

2020-11-06 14:15 UTC, farinalvaro commented on src/contracts/wrappers/contract-using-tokens.ts
> +      : this.supportedTokens[0].token
💯

2020-11-06 15:15 UTC, nduchak commented on src/contracts/interfaces.ts
> +  gasMultiplayer?: number
Done

2020-11-06 15:16 UTC, nduchak commented on src/contracts/interfaces.ts
> +}
hmm... why it's in the rates folder. For me, it looks like a global thing which related first of all to the contract part

2020-11-06 15:16 UTC, nduchak commented on src/contracts/wrappers/contract-using-tokens.ts
> +      : this.supportedTokens[0].token
=)

2020-11-06 15:26 UTC, farinalvaro commented on src/contracts/interfaces.ts
> +}
I agree, what I meant is that we should avoid duplicating that info

2020-11-06 15:30 UTC, nduchak commented on src/contracts/interfaces.ts
> +}
so, can I remove this from rates?

2020-11-06 15:32 UTC, nduchak commented on src/contracts/interfaces.ts
> +}
it's a quite big change in different files. I will include that in refactor PR

2020-11-06 15:54 UTC, farinalvaro commented on src/contracts/interfaces.ts
> +}
Yes, I agree it's quite a big change and could be tackled in different PR.
May be import it from rates and export here and then remove from rates in the refactor PR?
It would still be in the wrong place, but at least it won't be duplicated.

2020-11-06 19:01 UTC, jurajpiar requested changes
Nice work.
Could you just address following concerns of mine?

2020-11-06 19:14 UTC, jurajpiar commented on src/contracts/interfaces.ts
> +}
Yes, I'd certainly advise against repeating constants. If their location is a problem (which, admittedly, it may well be), create an issue for adjustment. I don't think it's necessary to import and export it here again, since the refactor (the issue) would address all places of occurrence.
I'm guessing you created it to make comparisons across this PR cleaner, ie to avoid using strings in if statements. However, there is a trade off with using enums vs string literal types. If preserving efficiency is prioritised enums should be avoided as they trans-pile to a very inefficient nested function.

2020-11-07 17:19 UTC, nduchak commented on src/contracts/wrappers/contract-base.ts
> +    this.contract = new web3.eth.Contract(abi, address)
Done

2020-11-07 17:19 UTC, nduchak commented on src/contracts/wrappers/contract-base.ts
> +    let { gasPrice, gas } = txOptions
I can not make it immutable as gas calculation depends on gasPrice

2020-11-07 17:22 UTC, nduchak commented on src/contracts/wrappers/contract-using-tokens.ts
> +  ) {
now it's has only 4 args is it fine to keep it as is?

2020-11-07 21:54 UTC, jurajpiar commented on src/contracts/wrappers/contract-using-tokens.ts
> +  ) {
Yea I guess that's borderline ;)

2020-11-18 11:33 UTC, closed without merging