feat(storage): adds ability for consumer to withdraw funds from an agreement
rsksmart/rif-marketplace-ui pull request #451
Opened 2020-11-04 14:41 UTC by farinalvaro

2020-11-06 19:29 UTC, jurajpiar requested changes
Please consider extracting a context as suggested bellow.

2020-11-06 19:29 UTC, jurajpiar commented on src/components/pages/storage/myPurchases/Page.tsx
> +      reportError(new UIError({
I'd rather have this handled in a Context. There is an awful lot of lines that could be moved there.
Just wrap it in a small context. It would take a load of this component and split responsibilities.

2020-11-10 13:53 UTC, farinalvaro commented on src/components/pages/storage/myPurchases/Page.tsx
> +      reportError(new UIError({
Done 🙂

2020-11-10 17:12 UTC, jurajpiar approved these changes

2020-11-10 17:35 UTC, merged