feat: refactor contracts wrappers
rsksmart/rif-marketplace-ui pull request #472
Opened 2020-11-10 10:05 UTC by nduchak

2020-11-19 14:28 UTC, jurajpiar requested changes
Looks good.
It's only so many comments because of absolute paths and because I commented on older issues that, however are included in this PR.

2020-11-19 14:28 UTC, jurajpiar commented on src/contracts/tokens/rif/erc20.ts
> +
absolute paths

2020-11-19 14:28 UTC, jurajpiar commented on src/contracts/tokens/rif/erc677.ts
> +import { TransactionOptions } from '../../interfaces'
absolute paths

2020-11-19 14:28 UTC, jurajpiar commented on src/contracts/wrappers/contract-base.ts
> +import withWaitForReceipt from '../utils'
absolute paths

2020-11-19 17:44 UTC, nduchak commented on src/contracts/rns/Marketplace.ts
> +    const unplaceTx = this.contract.methods.unplace(tokenId)
Good idea

2020-11-20 09:46 UTC, nduchak commented on src/contracts/storage/Staking.ts
> +const extraGasPercentage = 1.3
I just move it as a static property of Contract

2020-11-20 10:43 UTC, nduchak commented on src/ui-config.json
> +            "storageStaking": "0x99750Da185B646E56DdBDc80dd3263e2166bcb3f"
Reverted

2020-11-20 11:39 UTC, nduchak commented on src/contracts/storage/Staking.ts
> +const zeroBytes = '0x'.padEnd(64, '0')
Done

2020-11-20 11:48 UTC, jurajpiar approved these changes
👍

2020-11-20 12:55 UTC, farinalvaro approved these changes
LRGTM - Nothing to add after Juraj's review 🕵️‍♂️

2020-11-20 13:17 UTC, merged