feat(storage): adds ability to check for whitelisted storage providers
rsksmart/rif-marketplace-ui pull request #492
Opened 2020-11-16 20:36 UTC by farinalvaro

- adds storage global context to handle shared storage props (in a future refactor we could handle the contract instance here)

2020-11-17 14:58 UTC, farinalvaro commented on src/components/pages/storage/StorageRoutes.tsx
> +            <Switch>
Just to avoid confusion, the only change on this file was put the `StorageContextProvider` under `TabsTemplate`, all the other changes seem to be because of indentation

2020-11-17 16:20 UTC, jurajpiar commented on src/components/pages/storage/StorageRoutes.tsx
> +            <Switch>
thanks for that clarification.

2020-11-17 23:11 UTC, jurajpiar requested changes
Could you please provide some clarification as to why it is necessary to use service-wide context to implement this feature?

2020-11-17 23:11 UTC, jurajpiar commented on src/components/pages/storage/StorageRoutes.tsx
> +          <StorageContextProvider>
I don't understand why this needs to be service-wide context (what irony... :p). Isn't this only useful and used for creating an offer, as the [ticket](https://github.com/rsksmart/rif-marketplace-ui/issues/454) suggests?

2020-11-18 13:06 UTC, farinalvaro commented on src/components/organisms/storage/staking/Staking.tsx
> +  const isDisabled = !account || !isWhitelistedProvider
Good idea 🙂

2020-11-18 13:14 UTC, farinalvaro commented on src/components/pages/storage/sell/StorageSellPage.tsx
> +        && isWhitelistedProvider === false
Actually not, if we don't know if the provider is whitelisted (`isWhitelistedProvider 
 == undefined`) we disable some functionalities, but we don't want to show this message until we know if the account is not whitelisted.

2020-11-18 13:18 UTC, farinalvaro commented on src/components/pages/storage/StorageRoutes.tsx
> +          <StorageContextProvider>
Yes, I should have clarified that we also need this for staking. So, I think that having this in a global Storage context has the benefit of calculating it only once, but I'm open to better ideas 🙂

2020-11-18 16:16 UTC, jurajpiar approved these changes
䷯✔️ LGTM

2020-11-18 18:32 UTC, jurajpiar approved these changes

2020-11-18 18:33 UTC, merged