feat(storage): filters and fetches limits by available size
rsksmart/rif-marketplace-ui pull request #518
Opened 2020-11-23 19:58 UTC by farinalvaro

Closes #460 
Depends on https://github.com/rsksmart/rif-marketplace-cache/pull/414

2020-11-25 09:29 UTC, jurajpiar requested changes
Nice one. Could you just fix those bits where you copied old code stinks, please?

2020-11-25 09:29 UTC, jurajpiar commented on src/context/Services/storage/offers/OffersContext.tsx
> +  if (apiAvailableCapacity && !apiAvailableCapacity.service) {
`apiAvailableCapacity` will always be true in compile time (`appState?.apis?.['storage/v0/availableCapacity'] as AvailableCapacityService`)
as well as runtime as the apis are all instantiated from within the `appContext`
Now, I know that's how it is being done in that file, but maybe you could remove the check for the api object in the other two if statements, as well?
This also means changing `appState?.apis?.[...` to `appState.apis[...`.

2020-11-25 09:29 UTC, jurajpiar commented on src/context/Services/storage/offers/OffersContext.tsx
> +    apiAvailableCapacity.connect(errorReporterFactory(appDispatch))
Also here the errorReporterFactory could be called only once and reused (please change to other likes too)

2020-11-25 09:29 UTC, jurajpiar commented on src/api/rif-marketplace-cache/storage/available-size.ts
> +    const { min: minMB, max: maxMB } = await this.service.get(1)
```suggestion
    const { min: minMB, max: maxMB } = await this.service.get(1) // 1 required by service iface
```

2020-11-25 19:15 UTC, farinalvaro commented on src/context/Services/storage/offers/OffersContext.tsx
> +  if (apiAvailableCapacity && !apiAvailableCapacity.service) {
Done, thanks

2020-11-25 19:15 UTC, farinalvaro commented on src/context/Services/storage/offers/OffersContext.tsx
> +    apiAvailableCapacity.connect(errorReporterFactory(appDispatch))
Done, thanks

2020-11-25 19:15 UTC, farinalvaro commented on src/api/rif-marketplace-cache/storage/available-size.ts
> +    const { min: minMB, max: maxMB } = await this.service.get(1)
Done, thanks

2020-11-26 15:27 UTC, jurajpiar approved these changes

2020-11-26 16:31 UTC, merged