feat(storage): uses totalCapacity for offer edition/creation
rsksmart/rif-marketplace-ui pull request #525
Opened 2020-11-24 19:42 UTC by farinalvaro

2020-11-25 09:53 UTC, jurajpiar requested changes
👾 Just noticed the unnecessary object we're passing around.

2020-11-25 09:53 UTC, jurajpiar commented on src/components/organisms/storage/sell/EditOfferStepper.tsx
> +      totalCapacity, system, peerId, originalOffer,
perhaps just pass the `utilizedCapacityGB`, since the component doesn't use anything else from the object.

2020-11-25 09:53 UTC, jurajpiar commented on src/components/organisms/storage/sell/GeneralFeatures.tsx
> +      totalCapacity, system, peerId, originalOffer,
same here. just pass `utilisedCapacityGB`

2020-11-25 09:53 UTC, jurajpiar commented on src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
> +      originalOffer, billingPlans, totalCapacity, peerId,
again no need for the whole original offer object. the `transformOfferDataForContract` only uses the `subscriptionOptions`

2020-11-25 09:53 UTC, jurajpiar commented on src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
> +  const isSubmitEnabled = !!(billingPlans.length && totalCapacity)
```suggestion
  const isSubmitEnabled = Boolean(billingPlans.length && totalCapacity)
```

2020-11-25 09:53 UTC, jurajpiar commented on src/contracts/storage/utils.ts
>    originalOffer?: StorageOffer,
just pass `subscriptionOptions`

2020-11-25 19:21 UTC, farinalvaro commented on src/components/organisms/storage/sell/EditOfferStepper.tsx
> +      totalCapacity, system, peerId, originalOffer,
The problem with that is that `originalOffer` could be `undefined` because the same component is being used for offer creations and in that case we don't store a copy of the `originalOffer`

2020-11-25 19:22 UTC, farinalvaro commented on src/components/organisms/storage/sell/GeneralFeatures.tsx
> +      totalCapacity, system, peerId, originalOffer,
Same thing + we need to know if `originalOffer` is not undefined and in that case disable the `peerId` field.

2020-11-25 19:38 UTC, farinalvaro commented on src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
> +      originalOffer, billingPlans, totalCapacity, peerId,
We need the `originalOffer` that was set previously on `My Offers` page, if it was not set then we redirect to My Offers page, similar to what we do with orders in checkout

2020-11-25 19:59 UTC, farinalvaro commented on src/contracts/storage/utils.ts
>    originalOffer?: StorageOffer,
Done, thanks.
Just to left some guidance for the future I want to link https://github.com/rsksmart/rif-marketplace-ui/issues/377 with this change

2020-11-26 15:28 UTC, jurajpiar submitted a review, later dismissed

2020-11-26 16:55 UTC, jurajpiar approved these changes

2020-11-26 16:55 UTC, merged