fix(storage): passes the uploaded size
rsksmart/rif-marketplace-ui pull request #549
Opened 2020-11-27 17:56 UTC by jurajpiar

2020-11-27 18:45 UTC, farinalvaro requested changes
Nice! Just left some suggestions and a couple of questions.

2020-11-27 18:45 UTC, farinalvaro commented on src/api/rif-storage-upload-service/upload/index.ts
> +      return data
don't need to await here as the return type is already a Promise
```suggestion
      return response.json()
```

2020-11-27 18:45 UTC, farinalvaro commented on src/api/rif-storage-upload-service/upload/interfaces.ts
> +    fileSize: number
shouldn't size be `Big` type?

2020-11-27 18:45 UTC, farinalvaro commented on src/api/rif-storage-upload-service/upload/interfaces.ts
> +    fileSizeBytes: number
shouldn't size be Big type?

2020-11-27 18:45 UTC, farinalvaro commented on src/components/molecules/storage/upload/StorageUploaded.tsx
>      </GridItem>
Should we render this `GridItem` if uploadResponse is undefined?

2020-11-27 18:45 UTC, farinalvaro commented on src/components/organisms/storage/buy/PinningCard.tsx
>            UNIT_PREFIX_POW2.MEGA).toString()}
Would be clearer if extracted to constant I think

2020-11-27 18:45 UTC, farinalvaro commented on src/components/organisms/storage/buy/PinningCard.tsx
>              filesLimit={666 * 666 * 666}
not related to this PR but what is this value? 😈

2020-11-27 18:45 UTC, farinalvaro commented on src/components/organisms/storage/buy/PinningCard.tsx
>                setFiles(addedFiles)
I think this function could be cleaner if extracted

2020-11-27 19:54 UTC, jurajpiar commented on src/components/organisms/storage/buy/PinningCard.tsx
>                setFiles(addedFiles)
Disagree

2020-11-27 19:55 UTC, jurajpiar commented on src/components/organisms/storage/buy/PinningCard.tsx
>              filesLimit={666 * 666 * 666}
295,408,296

2020-11-27 19:56 UTC, jurajpiar commented on src/components/molecules/storage/upload/StorageUploaded.tsx
>      </GridItem>
No it's always defined in runtime I think

2020-11-27 19:57 UTC, jurajpiar commented on src/api/rif-storage-upload-service/upload/interfaces.ts
> +    fileSize: number
Nope

2020-11-27 20:06 UTC, jurajpiar commented on src/api/rif-storage-upload-service/upload/interfaces.ts
> +    fileSizeBytes: number
Nope

2020-11-27 20:08 UTC, jurajpiar commented on src/api/rif-storage-upload-service/upload/index.ts
> +      return data
No actually just forgot to map it

2020-11-30 08:24 UTC, jurajpiar commented on src/components/organisms/storage/buy/PinningCard.tsx
>              filesLimit={666 * 666 * 666}
If that's not sufficiently large I can do Big(6).pow(6).pow(6) instead .]

2020-11-30 08:53 UTC, jurajpiar commented on src/components/organisms/storage/buy/PinningCard.tsx
>              filesLimit={666 * 666 * 666}
should you want to know more about this number: https://numbermatics.com/n/295408296/

2020-11-30 08:54 UTC, jurajpiar commented on src/components/molecules/storage/upload/StorageUploaded.tsx
>      </GridItem>
Adapted the component disallow optional uploadResponse

2020-11-30 09:01 UTC, jurajpiar commented on src/api/rif-storage-upload-service/upload/interfaces.ts
> +    fileSize: number
no we receive and process it as Number

2020-11-30 09:01 UTC, jurajpiar commented on src/api/rif-storage-upload-service/upload/interfaces.ts
> +    fileSizeBytes: number
no we receive and process it as Number

2020-11-30 09:03 UTC, jurajpiar commented on src/api/rif-storage-upload-service/upload/interfaces.ts
> +    fileSizeBytes: number
no we receive and process it as Number

2020-11-30 13:53 UTC, farinalvaro approved these changes
👌

2020-11-30 13:54 UTC, merged