feat: add GitHub Action for Continuous Deployment
rsksmart/rif-marketplace-ui pull request #559
Opened 2020-11-30 14:51 UTC by lucasvuotto

Additional configuration steps will be needed before merging, which I'll follow up in private. Also, a tentatively deploy strategy is presented, but needs approval of the team before merging.

The tentatively deploy strategy is:
- Pushes to tags in the form of `vX.Y.Z` are deployed to all the environments
- Pushes to tags in the form of `vX.Y.Z-additional-data` are deployed just to staging environtment

2020-12-01 09:03 UTC, jurajpiar approved these changes
LGTM

2021-02-26 18:42 UTC, rafaiovlabs commented
bout this PR, basically team must be ok with the deployment scheme proposed:
The tentatively deploy strategy is:

Pushes to tags in the form of vX.Y.Z are deployed to all the environments
Pushes to tags in the form of vX.Y.Z-additional-data are deployed just to staging environment

If ok I can then do some configurations on the Repo.

2021-03-01 17:11 UTC, artem-brazhnikov requested changes

2021-03-01 17:11 UTC, artem-brazhnikov commented on .github/workflows/staging.yml
> +    tags:
I think as we agreed, we have to connect staging area to a branch

2021-03-01 18:30 UTC, rafaiovlabs commented on .github/workflows/staging.yml
> +    tags:
Yes, at the moment the "staging" branch is deployed to the "staging" bucket.

2021-03-09 15:40 UTC, closed without merging

2021-03-09 15:41 UTC, rafaiovlabs commented
We are closing this in favor of PR #745