feat(storage): avoids multiple offers creation
rsksmart/rif-marketplace-ui pull request #563
Opened 2020-12-02 12:13 UTC by farinalvaro

2020-12-02 18:52 UTC, jurajpiar requested changes
Please consider the comments...

2020-12-02 18:52 UTC, jurajpiar commented on src/components/pages/storage/sell/Page.tsx
> +      {renderContent()}
seems unnecessary. just put the content here no?

2020-12-02 18:52 UTC, jurajpiar commented on src/components/pages/storage/sell/Page.tsx
> +  }, [account, appDispatch, appState])
I'd prefer you put this in the context provider.

2020-12-02 18:52 UTC, jurajpiar commented on src/components/pages/storage/sell/NoMultipleOffers.tsx
> +    </Grid>
Not sure the extraction is needed. Consider rendering it directly in the sell page. My argument is that if you take the out the stuff that should be in the context the component wont get much bigger by having this code in.

2020-12-02 18:52 UTC, jurajpiar commented on src/components/pages/storage/sell/NoMultipleOffers.tsx
> +const NoMultipleOffers: FC = () => {
If you are going to keep this extraction, as I suspect you will, then rename it to something more telling of the job of this component. Basically it needs a noun in the name. And although "offers" IS as noun, in this combination it acts more as an adjective. So, NoMultipleOffers ... what? I'd say NoMultipleOffersCard would be the minimal effort acceptable change.

2020-12-02 19:02 UTC, farinalvaro commented on src/components/pages/storage/sell/Page.tsx
> +  }, [account, appDispatch, appState])
There is no context provider for this page and I think it's its responsibility to know if there's an offer created and so act based on that.
To me it seems like creating a context only to fetch an offer would add more complexity. I just wanted to keep it simple

2020-12-02 19:02 UTC, farinalvaro commented on src/components/pages/storage/sell/Page.tsx
> +      {renderContent()}
I just thought it was cleaner as this is a conditional component. Let me know if you still want me to move this.

2020-12-02 19:03 UTC, farinalvaro commented on src/components/pages/storage/sell/NoMultipleOffers.tsx
> +    </Grid>
What's the disadvantage of having it as a separated component? I find this cleaner and with better performance

2020-12-02 20:34 UTC, farinalvaro commented on src/components/pages/storage/sell/NoMultipleOffers.tsx
> +    </Grid>
Resolving after our chat

2020-12-02 20:35 UTC, farinalvaro commented on src/components/pages/storage/sell/NoMultipleOffers.tsx
> +const NoMultipleOffers: FC = () => {
Resolving after our chat

2020-12-02 20:35 UTC, farinalvaro commented on src/components/pages/storage/sell/Page.tsx
> +  }, [account, appDispatch, appState])
Resolving after our chat

2020-12-03 00:29 UTC, julianmrodri reviewed
Texting and wording changes. Besides that is Ok.

2020-12-03 00:29 UTC, julianmrodri commented on src/components/pages/storage/sell/NoMultipleOffersPage.tsx
> +            Creation of multiple offers is not supported yet.
I would change the message to a more positive like: "An offer is already created for the selected account."

2020-12-03 00:29 UTC, julianmrodri commented on src/components/pages/storage/sell/NoMultipleOffersPage.tsx
> +            {'You can edit your current offer on '}
```suggestion
            {'You can edit your current offer in '}
```

2020-12-03 10:56 UTC, jurajpiar reviewed
Please consider the comments...

2020-12-03 10:56 UTC, jurajpiar commented on src/components/pages/storage/sell/Wrapper.tsx
> +const Wrapper: FC = () => {
consider naming it `OfferPageWrapper` instead

2020-12-03 12:09 UTC, farinalvaro commented on src/components/pages/storage/sell/Wrapper.tsx
> +const Wrapper: FC = () => {
Done

2020-12-03 12:11 UTC, jurajpiar submitted a review, later dismissed

2020-12-03 14:14 UTC, jurajpiar approved these changes

2020-12-03 14:18 UTC, merged