feat(confirmations): adds confirmations context
rsksmart/rif-marketplace-ui pull request #594
Opened 2020-12-11 20:08 UTC by farinalvaro

`BlockchainContext` and `ConfirmationsContext` should be the same, but for the matter of transition I've created `ConfirmationsContext` to handle confirmations in a new way without interfering with `BlockchainContext` that's being used in many other services

Will close #586

2020-12-15 10:17 UTC, jurajpiar commented on src/components/pages/storage/myPurchases/Page.tsx
> +        && !!awaitingServices.Agreements.length
`Boolean(awaitingServices?.Agreements?.length)`

2020-12-17 12:11 UTC, jurajpiar requested changes
Good job. Please see my comments:

2020-12-17 12:11 UTC, jurajpiar commented on src/context/Confirmations/Context.tsx
> +    if (service && !isInitialised && account) {
the `isInitialised` will prevent re-authentication upon account change. might not be an issue atm, as when account changes we go back to home page. Once we fix that (assuming we will) though, it will be unable to re-auth as the `isInitialised` will be true by that point.

2020-12-17 12:11 UTC, jurajpiar commented on src/context/Confirmations/actions.ts
> +      delete confirmations[transactionHash]
Could we do this without mutating the argument, please.

2020-12-17 12:11 UTC, jurajpiar commented on src/context/Confirmations/actions.ts
> +      confirmationRecord.targetCount = targetConfirmation
same here

2020-12-17 12:55 UTC, farinalvaro commented on src/components/pages/storage/myPurchases/Page.tsx
> +           ${maybePluralize(confAwaitersKeys.length, 'agreement')}`}
I understand your point but I would prefer to not lose precision for a problem that doesn't exist now. Also the suffix is parametrized so we can set any depending on the noun or the language we want to use.
Is that convincing or should I make that change anyway?

2020-12-17 13:00 UTC, farinalvaro commented on src/context/Confirmations/Context.tsx
> +    if (service && !isInitialised && account) {
Good point. May be that's something that needs to be considered if and when we want to change the functionality of refreshing and going to home on account change, as this logic is being used in many contexts with services, right?

2020-12-17 15:09 UTC, farinalvaro commented on src/context/Confirmations/actions.ts
> +      confirmationRecord.targetCount = targetConfirmation
Done. confirmationRecord comes from the copy now

2020-12-17 16:01 UTC, farinalvaro commented on src/context/Confirmations/utils.ts
> +)
Good point, thanks 🙂

2020-12-17 16:35 UTC, jurajpiar approved these changes
✌️

2020-12-17 16:36 UTC, julianmrodri approved these changes
LGTM

2020-12-17 16:46 UTC, merged