feat(rns): adds multi-currency for placing and buying
rsksmart/rif-marketplace-ui pull request #651
Opened 2021-01-16 15:37 UTC by jurajpiar

Resolves [RMKT-148](https://rsklabs.atlassian.net/browse/RMKT-148)

2021-01-18 16:29 UTC, julianmrodri requested changes
We detected this is not using the attribute in Config file to define which currencies use per service. So I created a separate issue for this.

2021-01-19 08:47 UTC, jurajpiar commented
> We detected this is not using the attribute in Config file to define which currencies use per service. So I created a separate issue for this.

Juli I thought we'd use a separate hotfix PR? It does'n

2021-01-19 14:29 UTC, farinalvaro submitted a review, later dismissed
LGTM - just some minor comments

2021-01-19 14:29 UTC, farinalvaro commented on src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
> +      const currency = crypto[paymentToken]
```suggestion
      const { symbol } = crypto[paymentToken]
```
If `symbol` is the only prop needed from currency

2021-01-19 14:29 UTC, farinalvaro commented on src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
> +  }, [web3, account, tokenId, isFundsConfirmed, reportError, domainName, appDispatch, crypto, order])
Is it possible to remove `tokenId` dependency? As it comes from the `order` obj that is already a dependency of this `useEffect`

2021-01-19 14:29 UTC, farinalvaro commented on src/components/pages/rns/sell/DomainCheckoutPage.tsx
> +          === currencySymbols[Number(currency)])
Could be more readable if extracted into small function `getPaymentTokenFrom(currency)`?

2021-01-19 14:29 UTC, farinalvaro commented on src/contracts/rns/Rns.ts
> +    text: `Contract name ${paymentTokenSymbol} is not supported. Check SupportedTokens.`,
```suggestion
    text: `Token ${paymentTokenSymbol} is not supported. Check SupportedTokens.`,
```

2021-01-19 14:29 UTC, farinalvaro commented on src/contracts/rns/Rns.ts
> +    return toBN(myBalance).gte(toBN(price))
Nice!

2021-01-19 16:29 UTC, jurajpiar commented on src/components/pages/rns/sell/DomainCheckoutPage.tsx
> +          === currencySymbols[Number(currency)])
wouldn't go overboard with refactoring this file since it needs much bigger refactor. but ok...

2021-01-19 16:46 UTC, farinalvaro submitted a review, later dismissed

2021-01-19 17:27 UTC, julianmrodri submitted a review, later dismissed
LGTM

2021-01-20 12:09 UTC, farinalvaro commented on src/contracts/config.ts
> +// ?juraj - sparate payment token addresses
👀

2021-01-20 12:09 UTC, farinalvaro commented on src/contracts/rns/Rns.ts
> +  public async getPriceString(tokenId, account): Promise<string> { // ?juraj - account from web3?
👀

2021-01-20 12:10 UTC, jurajpiar commented on src/contracts/rns/Rns.ts
> +  public async getPriceString(tokenId, account): Promise<string> { // ?juraj - account from web3?
ah thanks

2021-01-20 12:12 UTC, jurajpiar commented on src/contracts/rns/Rns.ts
> +  public async getPriceString(tokenId, account): Promise<string> { // ?juraj - account from web3?
that means I made mistakes when rebasing... darn

2021-01-20 19:54 UTC, farinalvaro approved these changes
LGTM

2021-01-20 20:04 UTC, merged