feat(rns-sell): tracks placed domain confirmations
rsksmart/rif-marketplace-ui pull request #693
Opened 2021-02-02 18:35 UTC by farinalvaro

- removes domain placed page component and route
- fixes linter warnings
- imports MUI modules separately

Related to #607

2021-02-02 20:03 UTC, julianmrodri approved these changes
LGTM

2021-02-03 10:55 UTC, jurajpiar requested changes
LG just use the contract wrapper for getting the price please

2021-02-03 10:55 UTC, jurajpiar commented on src/components/pages/rns/sell/DomainCheckoutPage.tsx
> +      const gasPrice = await (web3 as Web3).eth.getGasPrice()
please, change this to use the rns contract wrapper

2021-02-03 10:55 UTC, jurajpiar commented on src/components/pages/rns/sell/DomainCheckoutPage.tsx
> +    const priceNumber = validatedNumber(value)
rename to `newPrice`

2021-02-03 16:17 UTC, farinalvaro commented on src/components/pages/rns/sell/DomainCheckoutPage.tsx
> +      const gasPrice = await (web3 as Web3).eth.getGasPrice()
In a new PR may be? As this was not changed in this PR and is out of scope of confirmations handling IMO

2021-02-03 16:18 UTC, farinalvaro commented on src/components/pages/rns/sell/DomainCheckoutPage.tsx
> +    const priceNumber = validatedNumber(value)
Done

2021-02-03 16:28 UTC, jurajpiar commented on src/components/pages/rns/sell/DomainCheckoutPage.tsx
> +      const gasPrice = await (web3 as Web3).eth.getGasPrice()
I disagree as the only change is a refactor:
```suggestion
      const gasPrice = await rnsContract.gasPrice()
```

That really doesn't require a separate PR. Only if you wanted to move the catch to rns, but since the function isn't used anywhere else left of the contract itself it wouldn't be a large change enough for own PR. In the master history this could appear as `refactor(rns): get price from wrapper`.

2021-02-03 17:27 UTC, jurajpiar approved these changes

2021-02-03 17:27 UTC, merged