fix(rns): adds limit to offers request
rsksmart/rif-marketplace-ui pull request #697
Opened 2021-02-04 15:47 UTC by jurajpiar

to restore pagination in domain offers

Resolves https://github.com/rsksmart/rif-marketplace-cache/issues/528
Related to https://github.com/rsksmart/rif-marketplace-cache/pull/529

2021-02-04 16:24 UTC, julianmrodri requested changes
Initial pagination works fine, but the Pagination is not updated once you change the filter. That used to work before. Look at the current image where I have 1-10/12. but only 6 results due to changing the filter. 

![image](https://user-images.githubusercontent.com/56316686/106922904-491ec380-66ec-11eb-9d4c-71aa79ee48d5.png)

2021-02-07 14:19 UTC, jurajpiar commented
> Initial pagination works fine, but the Pagination is not updated once you change the filter. That used to work before. Look at the current image where I have 1-10/12. but only 6 results due to changing the filter.
> 
> ![image](https://user-images.githubusercontent.com/56316686/106922904-491ec380-66ec-11eb-9d4c-71aa79ee48d5.png)

Done https://github.com/rsksmart/rif-marketplace-cache/pull/529#issuecomment-774681718

2021-02-09 12:12 UTC, julianmrodri approved these changes
LGTM

2021-02-09 14:31 UTC, farinalvaro approved these changes

2021-02-12 14:42 UTC, merged