feat(triggers): adds adds contract wrapper
rsksmart/rif-marketplace-ui pull request #717
Opened 2021-02-11 20:05 UTC by farinalvaro

2021-02-20 18:23 UTC, jurajpiar requested changes
Nice one.
Just got a suggestion regarding the action names and I'd like to bring back the discussion about using context for the page.

2021-02-20 18:23 UTC, jurajpiar commented on src/context/Confirmations/interfaces.ts
> +type NotifierContractAction = 'NOTIFIER_REGISTER_PROVIDER'
I suggest for these and other string literal types (those that will need to be written out for runtime at some point) to use following const assertion:
```TypeScript
export const notifierContractAction = 'NOTIFIER_REGISTER_PROVIDER' as const
```
and then if needed as type on its own:
```TypeScript
export type NotifierContractAction = typeof notifierContractAction
```
or directly in the `ContractAction` union type:
```TypeScript
export type ContractAction = 
| typeof notifierContractAction
...
```
this will give us the ability to use the constant when needed to insert action name.

2021-02-22 13:33 UTC, farinalvaro commented on src/components/pages/notifier/sell/NotifierSellPage.tsx
> +  }
What would be the advantage of creating a context for this?
IMO it would result in a more complex solution as there is no state or props to be shared between components, everything is local to this component so here it should be. Ref: [When to use context](https://reactjs.org/docs/context.html#when-to-use-context)

2021-02-22 14:15 UTC, jurajpiar commented on src/components/pages/notifier/sell/NotifierSellPage.tsx
> +  }
Yes you are right. It's only that I like to extract contract interaction above the pages, as to separate concerns. That is let the page handle UI logic and not bother about the business logic.
Here I proposed to also handle the UI logic in the context just so that the page has no side-effects at all.
After the discussion in chat with Alvaro, I'm resolving the conversation without furter changes.

2021-02-22 18:24 UTC, farinalvaro commented on src/context/Confirmations/interfaces.ts
> +type NotifierContractAction = 'NOTIFIER_REGISTER_PROVIDER'
Ok, but it looks like a bigger refactor than just the type we are adding here. Would you be okay to do this in a separate PR?
I mean we would need to change all `ContractAction` types to make it consistent

2021-02-23 09:03 UTC, merged