Add staging workflow for CD
rsksmart/rif-marketplace-ui pull request #745
Opened 2021-03-03 13:13 UTC by rafaiovlabs

Staging workflow for CD of marketplace UI

2021-03-04 11:55 UTC, artem-brazhnikov approved these changes

2021-03-04 11:55 UTC, artem-brazhnikov commented on .github/workflows/staging.yml
> +      - staging
ok good, the dev env is approved, I will work on the branches workflow so it's consistent across repos

2021-03-09 15:31 UTC, jurajpiar requested changes
Change the commit message to follow the [conventional commit specs](https://www.conventionalcommits.org/en/v1.0.0/) please

2021-03-11 08:39 UTC, artem-brazhnikov commented
@jurajpiar @rafaiovlabs we need to find out why the pipeline is failing, I restarted the CI. There seemed to be an out of memory error.

2021-03-12 07:33 UTC, artem-brazhnikov commented
@rafaiovlabs can you please check the amount of memory allocated for the CI? I think it might not enough
https://discuss.circleci.com/t/unit-tests-enomem-not-enough-memory-read/35695/3

2021-03-12 07:52 UTC, artem-brazhnikov requested changes
Also, in the previous PR there were jobs for the testnet and mainnet. Why they disappeared in this one?

2021-03-12 07:52 UTC, artem-brazhnikov commented on .github/workflows/staging.yml
> +    tags:
@rafaiovlabs I was thinking through this and I am not sure we need to deploy tags to the staging. Image when we merged some piece of logic to staging and QA are working on it. And then we make a release from master and suddenly the QA are presented with a different version.

2021-03-12 18:02 UTC, rafaiovlabs commented on .github/workflows/staging.yml
> +    tags:
@artem-brazhnikov  Fixed the mem issue of CI with this PR, about the tags..i thing those give us better control (in dev environment they are not needed at all) , but for staging could be of benefit and also we can have tags like v2.3.0-qafix or something like that. About not having CD for other envs thats correct i only have staging precisely to validate the deployment, workflows and so on, after validation CD for other envs is trivial to add.

2021-03-16 11:44 UTC, artem-brazhnikov commented on .github/workflows/staging.yml
> +    tags:
ok, good

2021-03-16 11:46 UTC, artem-brazhnikov approved these changes

2021-03-16 11:46 UTC, artem-brazhnikov commented on .github/workflows/staging.yml
> +    tags:
ok, lets try and see how it goes

2021-03-16 11:47 UTC, merged