feat(triggers): adds offers api
rsksmart/rif-marketplace-ui pull request #753
Opened 2021-03-05 19:14 UTC by jurajpiar

2021-03-12 09:45 UTC, artem-brazhnikov requested changes

2021-03-12 09:45 UTC, artem-brazhnikov commented on src/api/rif-marketplace-cache/notifier/offers/models.ts
> +class TransportModel implements TransportModelType {
if you are implementing it's some interface - it's better to use the `interface` keyword and not use the `Type` word in its name

2021-03-12 09:45 UTC, artem-brazhnikov commented on src/api/rif-marketplace-cache/notifier/offers/models.ts
> +    public readonly toLocal = (): NotifierOfferItem => ({
you can just use a member function here I guess

2021-03-12 09:45 UTC, artem-brazhnikov commented on src/api/rif-marketplace-cache/notifier/interfaces.ts
> +export type NotifierAPIService = Modify<
The same here, I would call it an `interface` if it has a contract that needs implemented

2021-03-12 09:45 UTC, artem-brazhnikov commented on src/api/rif-marketplace-cache/notifier/offers/offers.ts
> +    private mapFromTransport: MapFromTransport<TransportModel, NotifierOfferItem> = (transport) => transport.toLocal()
can be expressed as a member function

2021-03-12 09:45 UTC, artem-brazhnikov commented on src/components/pages/notifier/buy/NotifierOffersPage.tsx
> +      })).sort()
why don't you write a single cycle that will go over the plans and make all the necessary transformations in one go?

2021-03-15 09:40 UTC, jurajpiar commented on src/api/rif-marketplace-cache/notifier/offers/models.ts
> +class TransportModel implements TransportModelType {
fair enough. though since I'm not planning on extending this interface it should remain a type ([src](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces))?
About the naming, yea I know. Wasn't sure what to call it tho. Got any suggestions?

2021-03-15 09:56 UTC, jurajpiar commented on src/api/rif-marketplace-cache/notifier/offers/models.ts
> +    public readonly toLocal = (): NotifierOfferItem => ({
Could you describe why it would be preferable?
I'm guessing you just mean to define it as:
```ts
class TransportModel {
   ...
   readonly toLocal() {
      ...
   }
}
```


In fact, this is something I've just tried out for this PR. Normally, we just use a type here and the mapping is left for the mapFromTransport function. The reason for this approach was that I thought it would be more easily testable once we refactor the base api class.
Anyways, I can and perhaps should return it back to match the rest of the app's implementation.

2021-03-15 09:59 UTC, jurajpiar commented on src/api/rif-marketplace-cache/notifier/interfaces.ts
> +export type NotifierAPIService = Modify<
as you can observe from the link in the previous comment, the difference between `type` and `interface` in TS is really in the extensibility not implementability, thus it only make sense to use `interface` when you expect the type to be extended.

2021-03-15 10:00 UTC, jurajpiar commented on src/api/rif-marketplace-cache/notifier/offers/offers.ts
> +    private mapFromTransport: MapFromTransport<TransportModel, NotifierOfferItem> = (transport) => transport.toLocal()
again, please give reason. Just because it can doesn't mean it should.

2021-03-15 10:14 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersPage.tsx
> +      })).sort()
That's exactly why I asked the reviewers to focus on this bit. If you look more closely each bit has different requirements for the mapping. For example, the `channels` needs to put it all in a `Set` to remove duplications, the `prices` needs to return a mapped inner parameter, then just the first and the last is used, and so on.
This complexity is the exact reason I kept it all in separate loops, so that we can see it better and discuss the best strategy.

Actually I just noticed the `currency` is wrong. It should display all currency options, so would be more similar to the `channels` in that it needs to be a `Set`.

2021-03-16 14:32 UTC, artem-brazhnikov approved these changes
LGTM

2021-03-16 15:01 UTC, merged