feat(devops): add develop workflow
rsksmart/rif-marketplace-ui pull request #834
Opened 2021-04-20 19:17 UTC by rafaiovlabs

2021-04-22 15:20 UTC, artem-brazhnikov approved these changes
looks good but needs to be tested

2021-04-22 15:22 UTC, artem-brazhnikov requested changes

2021-04-22 15:22 UTC, artem-brazhnikov commented on .github/workflows/develop.yml
> +  deploy-staging:
deploy-develop

2021-04-22 16:35 UTC, rafaiovlabs commented on .github/workflows/develop.yml
> +  deploy-staging:
done

2021-04-23 08:12 UTC, artem-brazhnikov approved these changes
LGTM

2021-05-11 16:46 UTC, jurajpiar approved these changes

2021-05-11 16:49 UTC, merged