Feature/addevents
rsksmart/rif-marketplace-ui pull request #837
Opened 2021-04-30 14:41 UTC by vjgene

Add NotifierOffersSelectedPage
List events in the page
Provide way to delete events

2021-05-03 07:09 UTC, artem-brazhnikov approved these changes
looks good to me, wait for @jurajpiar review before merging

2021-05-04 10:40 UTC, jurajpiar requested changes
Please, see the `NotifierMyOffersPage` for reference to the components required for this page.

2021-05-04 10:40 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +      </Table>
Please, use the `src/components/molecules/DescriptionCard.tsx`. Also, use `Grid` instead of `Table`, as that renders quite a different result and it's a bit overkill for a single raw. (See `NotifierMyOffersPage` and `NotifierProviderDescription`)

2021-05-04 10:40 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +      </Table>
Also, it is missing styling (via `Typography`). Again check the the mentioned components for reference.

2021-05-04 10:40 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +      </Table>
When inserting a table, please use the Marktetplace component. For reference, see `src/components/organisms/plans/PlanView.tsx`. Also missing Typography as well.

2021-05-04 10:40 UTC, jurajpiar commented on src/context/Services/notifier/offers/Context.tsx
> +import { SUPPORTED_TOKEN_RECORDS } from '../../../../contracts/interfaces'
prefer absolute paths

2021-05-04 10:40 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +import CenteredPageTemplate from '../../../templates/CenteredPageTemplate'
prefer absolute paths

2021-05-04 10:40 UTC, jurajpiar commented on src/context/Services/notifier/offers/__tests__/Context.test.tsx
> +import { SUPPORTED_TOKEN_RECORDS } from '../../../../../contracts/interfaces'
prefer absolute paths

2021-05-04 10:40 UTC, jurajpiar commented on src/context/Services/notifier/offers/Context.tsx
> +  },
no need for these here, as they'll only be used on this page. Move to local state, please.

2021-05-04 10:40 UTC, jurajpiar commented on src/context/Services/notifier/offers/Context.tsx
> +  },
why are you initialising the order? By default there can't be one, before you select something.

2021-05-04 10:40 UTC, jurajpiar commented on src/context/Services/notifier/offers/actions.ts
> +  },
there is no need for this as (un)setting the order should be sufficient. One order will, by design, always have only one item. See the the `ServiceOrder` type in `src/context/Services/interfaces.ts`.

2021-05-04 10:40 UTC, jurajpiar commented on src/models/marketItems/NotifierItem.ts
> +    channels: string
shouldn't this be `string[]`?

2021-05-04 10:40 UTC, jurajpiar commented on src/routes.ts
> +const SELECTED = 'selected'
remove and use checkout instead

2021-05-04 12:19 UTC, vjgene commented on src/models/marketItems/NotifierItem.ts
> +    channels: string
since the channels attribute are used for display only, it is of string type

2021-05-06 11:01 UTC, jurajpiar requested changes
A few more changes, sorry.

2021-05-06 11:01 UTC, jurajpiar commented on src/components/organisms/notifier/NotifierPlanDescription.tsx
> +export type NotifierOrder = OffersOrder | undefined | boolean
I don't understand this type. Doesn't look very safe, being both object and a boolean that is.
Why can't the item prop be defined just as `item?: OffersOrder`?

2021-05-06 11:01 UTC, jurajpiar commented on src/components/organisms/notifier/NotifierPlanDescription.tsx
> +}
Seems totally unnecessary, considering these fields never change.
You could just put them down statically. No need for two loops and a function with lots of if-statements.

2021-05-06 11:01 UTC, jurajpiar commented on src/components/pages/notifier/NotifierRoutes.tsx
> +                  <Route component={NotFound} />
Remove this line as it is covered by the DeadEndRoute constant on the previous line.

2021-05-06 11:01 UTC, jurajpiar commented on src/context/Services/notifier/offers/interfaces.ts
> +}
Remove as not used in this context.

2021-05-06 11:01 UTC, jurajpiar commented on src/context/Services/notifier/offers/interfaces.ts
> +  events?: NotifierEvents
Remove from Context. It should only be in a local (in-page) state.

2021-05-06 11:01 UTC, jurajpiar commented on src/models/marketItems/NotifierItem.ts
> +    actions: ReactElement
Remove actions from this type. You can extend it locally on the page if you need to add it, for example
`const [events, setEvents] = useState<NotifierEvents & { actions: React.ReactElement }>()`.

But that's still kinda wrong, because the items you pass to the table should all be components, rather than text, so that they can be individually styled. So, I'd suggest to remove this type from here altogether and instead type it on the page like so:
```
const eventHeaders = {
  name: 'Name',
  type: 'Type',
  signature: 'Signature',
  channels: 'Channels',
  actions: '',
}

type EventTableItem = Item & {
    [K in keyof typeof eventHeaders]: React.ReactElement
}
const [events, setEvents] = useState<Array<EventTableItem>>()

```

2021-05-06 11:01 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const RemoveButton: FC<string> = (id) => <Typography align="right" gutterBottom color="primary"><SelectRowButton size="large" variant="text" handleSelect={removeEvent} id={id}>X</SelectRowButton></
1. please, refactor this out into atoms folder
2. the 'X' should be replaced with `CloseIcon` imported from `@material-ui/icons/Close`
2. the `id` needs to be enclosed in curly brackets, but
3. the type should change to `FC<SelectRowButtonProps>`, that way you can spread the props to the `SelectRowButton`

2021-05-06 11:01 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +    }))
Seems unnecessary. You've already got the `events` constant that will satisfy the collection prop.
On the other hand, if you don not want to store components in the state (probably best not to), then you can do:
```
const eventHeaders = {
  name: 'Name',
  type: 'Type',
  signature: 'Signature',
  channels: 'Channels',
  actions: '',
} as const

type EventHeaders = typeof eventHeaders

type EventItem = Item & {
    [K in keyof Omit<EventHeaders, 'actions'>]: string
}

const [events, setEvents] = useState<Array<EventItem>>()

type EventTableItem = Item & {
   [K in keyof EventHeaders]: React.ReactElement
}

const collection = events.items
    .map<EventTableItem>((event) => ({
   ...
```

2021-05-06 11:01 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const RemoveButton: FC<string> = (id) => <Typography align="right" gutterBottom color="primary"><SelectRowButton size="large" variant="text" handleSelect={removeEvent} id={id}>X</SelectRowButton></
then in the mapping you'd use pass prop 
```
handleSelect={() => {
   const newEvents = [ ...events ]
   newEvents.splice(i, 1)
   setEvents(newEvents)
}}
```

2021-05-06 11:01 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +      provider: 0,
there is no provider key

2021-05-06 11:01 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +      ],
As I mentioned further down, either store values and map them to components, or store components so you don't have to map. Personally, I think the first one is better as storing components seems evil .]

2021-05-07 09:55 UTC, jurajpiar approved these changes
looking good, make sure to clean the commits before merging .]

2021-05-07 12:34 UTC, merged