feat(notifier): adds notification channels
rsksmart/rif-marketplace-ui pull request #842
Opened 2021-05-10 18:21 UTC by vjgene

Adds Notification channels section in notifier buy checkout page

2021-05-11 13:52 UTC, itofarina reviewed
Overall looks good. Just please consider those 2 comment:
- Template the component we wanted to reuse instead of copying it
- Use `react-hook-form` library for data input

2021-05-11 13:52 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationChannel.tsx
> +          </Grid>
Please, prefer classes instead of inline styles. See [this SO question](https://stackoverflow.com/questions/57791954/material-ui-why-should-i-use-makestyles-instead-of-inline-styles) for more info

2021-05-11 13:52 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationChannel.tsx
> +        >
If this is the same row styles we were talking about, I think it would be best to template it. That way we could reuse it here and if we want to change it in the future we would only need to do the change in one place.

2021-05-11 13:52 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +  return (
I know we have a lot of `Grid` components acting as forms, but we are trying to migrate them to https://react-hook-form.com/. With that we don't need to create validations for emails for example. It also improves UX.
See https://github.com/rsksmart/rif-marketplace-ui/issues/710 and https://github.com/rsksmart/rif-marketplace-ui/pull/709 for reference

2021-05-11 17:26 UTC, jurajpiar requested changes
A couple more changes from me too, please.

2021-05-11 17:26 UTC, jurajpiar commented on src/models/marketItems/NotifierItem.ts
> +}
Prefer using const assertion to enums, unless you'd benefit from bidirectional resolution. See https://tinyurl.com/enumconst

2021-05-11 17:26 UTC, jurajpiar commented on src/utils/validationUtils.ts
> +  return url.protocol === 'http:' || url.protocol === 'https:'
what about other protocols?

2021-05-11 17:26 UTC, jurajpiar commented on src/utils/validationUtils.ts
> +}
let's not validate emails in the UI.
1. expensive
2. doesn't actually validate the email address

once we do start using email in channels, we should send a verification email instead.

2021-05-11 17:26 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +      <br />
Use grid to position things on page instead.

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +      <br />
don't need this. use grid and/or jss

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +          collection.map((channel) => <NotificationChannel className={classes.notificationChannel} channel={channel} onRemoveClick={removeChannel} />)
split this to lines

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +    const newChannels = addedChannels.filter((i) => i.type !== e.currentTarget.id)
please use meaningful variable names (yea, even for iterator arguments)

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +    const index = addedChannels.findIndex((ch) => ch.type === notifierChannel.type)
please use meaningful variable names (yea, even for iterator arguments)

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +      return
use the forms dependency for validation, if needed. (would not worry about that right now tbh tho)

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +  const availableChannels: Array<string> = channels.map((ch) => (NotifierChannelType[ch] ? ch : ''))
please use meaningful variable names (yea, even for iterator arguments)

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +      type: e.target.value as string,
destructure {target} or {target: {value}}

2021-05-11 17:26 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +    destination: '',
I'd keep default undefined and render the `NotificationChannelCreate` conditionally

2021-05-12 08:57 UTC, vjgene commented on src/utils/validationUtils.ts
> +  return url.protocol === 'http:' || url.protocol === 'https:'
Notifier only supports http and https for rest calls as of now

2021-05-13 08:51 UTC, jurajpiar requested changes
A couple more bits & bobs.

2021-05-13 08:51 UTC, jurajpiar commented on src/utils/validationUtils.ts
> +  return url.protocol === 'http:' || url.protocol === 'https:'
I think it would be better to use a constant for the valid protocols. Also, we're trying to keep the use of mutable variables close to none. Another point is to try not to use arg names with underscore prefix. In fact I'm surprised eslint didn't complain about that. I suggest following structure:

```suggestion
const EVENT_API_AVAILABLE_PROTOCOLS = [ 'http:', 'https:'] // we could potentially make this configurable, for sure we should move it somewhere more in scope of the notifier service

const validateURLProtocol = (url: string, validProtocols: Array<string>): boolean => {
  try {
    const { protocol } = new URL(url)
    return validProtocols.includes(protocol);
  } catch { // note that catch in js doesn't need arguments
    return false
  }
}
```

2021-05-13 08:51 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +  const availableChannels: Array<string> = channels.map((channel) => (notifierChannelType[channel] ? channel : ''))
I get that you want to restrict the use to only those currently supported channels with this. If so, then we should make this either configurable, or a constant somewhere. However, one that represents this, like `const EVENT_AVAILABLE_CHANNELS = ['API']` (currently just that API I think. Is that right @artem-brazhnikov?).
Another thing here is that maybe use `.filter` instead of mapping to potentially empty string.

2021-05-13 08:51 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelCreate.tsx
> +export interface NotificationChannelCreateProps {
As not used outside just call it `Props`

2021-05-13 08:51 UTC, jurajpiar commented on src/models/marketItems/NotifierItem.ts
> +export const notifierChannelType = {
Sorry didn't pick up on this before, but let's call this `notifierChannelPlaceholder` and move it to the `src/components/organisms/notifier/NotificationChannelCreate.tsx ` as it is not needed for any other areas of the UI.

2021-05-14 09:57 UTC, jurajpiar approved these changes

2021-05-14 09:57 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelCreate.tsx
> +        <SelectRowButton id="add-channel" handleSelect={handleSubmit(() => channelAdd(notifierChannel))} size="large" variant="outlined">Add Channel</SelectRowButton>
split to multiple lines

2021-05-14 09:57 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +    channels: string[] | undefined
- `channels?: Array< SupportedEventChannel>`

2021-05-14 09:57 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +  const availableChannels: Array<string> = channels.filter((channel) => SUPPORTED_EVENT_CHANNELS.indexOf(channel as SupportedEventChannel) !== -1)
- multiple lines
- `const availableChannels: Array< SupportedEventChannel>`
- SUPPORTED_EVENT_CHANNELS.includes(channel)

2021-05-14 09:57 UTC, jurajpiar commented on src/utils/validationUtils.ts
> +export const EVENT_API_AVAILABLE_PROTOCOLS = ['http:', 'https:']
this should be in the notifier config now. (also could you please rename it to match the other const please? my bad, sorry)

2021-05-14 10:44 UTC, merged