Feature/addevents
rsksmart/rif-marketplace-ui pull request #849
Opened 2021-05-18 14:31 UTC by vjgene

Includes feature for adding smart contract events in notifier buy page

2021-05-19 15:18 UTC, artem-brazhnikov approved these changes
lgtm

2021-05-19 15:53 UTC, itofarina requested changes
The big picture and functionality looks great 👌 . I just think there are some things that could be improved for better reading.

2021-05-19 15:53 UTC, itofarina commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +  const [addedChannels, setChannels] = useState<Array<NotifierChannel>>([])
Please, use same name for updater and callback for easy reading.

```suggestion
  const [addedChannels, setAddedChannels] = useState<Array<NotifierChannel>>([])
```

2021-05-19 15:53 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +const NotificationChannelsList: FC<Props> = ({ channels, setEventChannels }) => {
```suggestion
const NotificationChannelsList: FC<Props> = ({ eventChannels, onEventChannelsUpdate }) => {
```

2021-05-19 15:53 UTC, itofarina commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +} from '@material-ui/core'
```suggestion
import Box from '@material-ui/core/Box'
import Typography from '@material-ui/core/Typography'
```

2021-05-19 15:53 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +    })
May we use the hook `useErrorReporter` here to report this error?

2021-05-19 15:53 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +          <RoundBtn onClick={handleSubmit(handleAddEvent)}>
I think this button could be disabled on the condition that returns empty for better UX:
```suggestion
          <RoundBtn disabled={() => !eventData?.addedChannels?.length || !eventData.event} onClick={handleSubmit(handleAddEvent)}>
```

2021-05-19 15:53 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +            }
Could we add this to errors prop in `react-hook-form`? Same as `errors.contract` so that we have all possible errors in the same place.

2021-05-19 15:53 UTC, farinalvaro commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                }
Please add unique `key` prop here for better performance. Could be the event name.

2021-05-19 15:53 UTC, farinalvaro commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
>  } from '@material-ui/core'
Please if possible, import from their own modules to reduce bundle size. For example: `import Box from '@material-ui/core/Box`

2021-05-19 15:53 UTC, farinalvaro commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +        name: notifierEvent.name as string,
I might be missing something but why having it repeated into 2 different props? Do we need the id or could we just reuse the name?

2021-05-19 15:53 UTC, farinalvaro commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const [addEvent, setAddEvent] = useState<boolean>(false)
```suggestion
  const [addEventCollapsed, setAddEventCollapsed] = useState<boolean>(false)
```

2021-05-19 15:53 UTC, farinalvaro commented on src/models/marketItems/NotifierItem.ts
> +    // filter?: string //todo: see if this parameter can be used
If not needed I would suggest to remove it to avoid confusion 😄

2021-05-20 10:05 UTC, vjgene commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +  const [addedChannels, setChannels] = useState<Array<NotifierChannel>>([])
done

2021-05-20 10:05 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +} from '@material-ui/core'
done

2021-05-20 10:05 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +          <RoundBtn onClick={handleSubmit(handleAddEvent)}>
done

2021-05-20 10:06 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +            }
this is not part of anyform.. it comes from child component

2021-05-20 10:06 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                }
done

2021-05-20 10:06 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +        name: notifierEvent.name as string,
removed id

2021-05-20 10:06 UTC, vjgene commented on src/models/marketItems/NotifierItem.ts
> +    // filter?: string //todo: see if this parameter can be used
done

2021-05-20 10:07 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const [addEvent, setAddEvent] = useState<boolean>(false)
done

2021-05-20 10:08 UTC, vjgene commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +const NotificationChannelsList: FC<Props> = ({ channels, setEventChannels }) => {
done

2021-05-20 22:02 UTC, jurajpiar requested changes
Few bits to do here, mainly removing state mutation. Also, please make sure you format the documents before pushing (maybe need to enable "format on save?").

2021-05-20 22:02 UTC, jurajpiar commented on src/api/blockscout/interface.ts
> +export type ContractABIEvent = Omit<ContractABIItem, 'type'|'outputs'|'payable'|'stateMutability'|'constant'>
maybe use `Pick<ContractABIItem, 'name' | 'inputs' | 'anonymous'>` instead?

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +        && eventData.event !== undefined) as boolean
```suggestion
  const canAddEvent = (): boolean => Boolean(eventData.addedChannels?.length && eventData.event)
```

2021-05-20 22:02 UTC, jurajpiar commented on src/config/notifier/index.ts
> +export type SupportedEvent = | 'SMARTCONTRACT' | 'NEWBLOCK'
I think it would be neater to use const assertion here to mimic enum. That way you don't have to cast it upon usage (which remains same otherwise) and "intellisense" will give you options`.
```suggestion
export type SupportedEventType = keyof typeof SUPPORTED_EVENTS
```
where supported events is defined as:
```
export const SUPPORTED_EVENTS: { 
   SMARTCONTRACT: 'SMARTCONTRACT',
   NEWBLOCK: 'NEWBLOCK' 
} as const
```

2021-05-20 22:02 UTC, jurajpiar commented on src/config/notifier/index.ts
> +export type SupportedEvent = | 'SMARTCONTRACT' | 'NEWBLOCK'
maybe do the same for SUPPORTED_EVENT_CHANNELS should you choose to go this route.

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +  const canAddEvent = (): boolean => (eventData?.addedChannels !== undefined
destructure eventData. it seems it is going to be always defined since you're using a default value.
another thing is, you don't need to use `!== undefined` as if it is it will be falsy. Equally with the `.length > 0`. 0 is a falsy value.

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +              value={eventData?.eventType ? eventData.eventType : (SUPPORTED_EVENTS.length ? SUPPORTED_EVENTS[0] : '')}
One thing: Please don't nest ternary operators.
Another, less important one is: `something ? something : else` can be better written as `something ?? else`.

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +        SUPPORTED_EVENTS.map((eventType) => <MenuItem key={eventType} value={eventType}>{notifierEventTypeLabels[eventType]}</MenuItem>)
please separate long lines. Ideally keep to the linter's warning threshold (I think it's 86).

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                value={eventData?.event?.name || (events.length ? events[0].name : '')}
no nested ternary operators please.

2021-05-20 22:02 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +const buildEventSignature = (notifierEvent: NotifierEvent): string => `${notifierEvent.name}(${notifierEvent?.params?.map((input: NotifierEventParam) => `${input.name} ${input.type}`).join(',')})`
waaay too long. also do the mapping ahead of building a string

2021-05-20 22:02 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +type EventItem = {
why did you remove the Item type? We use the id for such things as keys (for when react renders an array of elements)

2021-05-20 22:02 UTC, jurajpiar commented on src/api/blockscout/index.ts
> +  return abiItems.filter((abiItem: ContractABIItem) => abiItem.type === 'event').map((item) => item as ContractABIEvent)
line too long

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
>      const newChannels = [...addedChannels]
Could we change this this time around please?
```suggestion
    const existingChannel = addedChannels.find(({ type }) => type === notifierChannel.type)
    const newChannels = [...addedChannels]

    if (existingChannel) {
       newChannels.push(notifierChannel)
    } else {
       newChannels.destination = notifierChannel.destination
```
Especially the mutating state bit. Perhaps that is why you needed two states to hold your channels? now you can remove one as they are set together to the same values there is no need to have them both. Or am I missing something?

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +        text: error.text,
The `text` property here defines the error that will be shown to the user. So make something nice up as we cannot ensure that the api will return something meaningful to the enduser.

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +    setEventData({ ...eventData, event: events.filter((event) => event.name === value)[0] })
```suggestion
    setEventData({ ...eventData, event: events.find(({name}) => name === value) as EventData})
```
provided we can be sure the event will always be found, which I guess is true considering you used `[0]`.

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +        && eventData.event !== undefined) {
more of the same

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                  Atleast one notification channel must be added
```suggestion
                  At least one notification channel must be added
```
Maybe we could be friendlier, e.g. "Please add your first channel before continuing."? Or is this in the designs? (sorry didn't look)

2021-05-20 22:02 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +            }
Maybe it should be? Btw what do you mean by "it comes from child component"? In composition it is very unusual for anything other than eventHandlers (ok refs too) to come from a child component, isn't it? Perhaps is just too late for me.)

2021-05-21 07:36 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                  Atleast one notification channel must be added
we have removed this error as the submit button won't be enabled until channels are added

2021-05-21 08:06 UTC, jurajpiar commented on src/api/blockscout/interface.ts
> +export type ContractABIEvent = Omit<ContractABIItem, 'type'|'outputs'|'payable'|'stateMutability'|'constant'>
Or would the other way around make more sense? As in
```
export type ContractABIEvent = {
  name: string
  inputs?: Array<ContractABIEventParam>
  anonymous?: boolean
}

export type ContractABIItem = ContractABIEvent & {   
  type: string
  constant?: boolean
  outputs?: any
  payable?: boolean
  stateMutability?: string
}
```

2021-05-21 08:10 UTC, vjgene commented on src/api/blockscout/interface.ts
> +export type ContractABIEvent = Omit<ContractABIItem, 'type'|'outputs'|'payable'|'stateMutability'|'constant'>
done

2021-05-21 09:04 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +        text: error.text,
we are already catching the error and providing meaningful errors in blockscout/index.ts. this is just showing that error

2021-05-21 10:11 UTC, vjgene commented on src/config/notifier/index.ts
> +export type SupportedEvent = | 'SMARTCONTRACT' | 'NEWBLOCK'
done

2021-05-21 10:11 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +              value={eventData?.eventType ? eventData.eventType : (SUPPORTED_EVENTS.length ? SUPPORTED_EVENTS[0] : '')}
done

2021-05-21 10:12 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +  const canAddEvent = (): boolean => (eventData?.addedChannels !== undefined
done

2021-05-21 10:12 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +    setEventData({ ...eventData, event: events.filter((event) => event.name === value)[0] })
done

2021-05-21 10:12 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +        && eventData.event !== undefined) as boolean
done

2021-05-21 10:12 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +        && eventData.event !== undefined) {
done

2021-05-21 11:50 UTC, jurajpiar requested changes
Still missing resolution for some comments

2021-05-21 11:50 UTC, jurajpiar commented on src/api/blockscout/index.ts
> +  return abiItems.filter((abiItem: ContractABIItem) => abiItem.type === 'event').map((item) => item as ContractABIEvent)
Still present it seems.

2021-05-21 11:50 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
>      const newChannels = [...addedChannels]
This was the main reason I requested changes. Please do not mutate state.
Work off the cloned array from the start of the function. Also once again don't use index === -1, please. First, you don't need to use the index here, just get the object instead. then mutate the object. const existingChannel = channelsClone.find(({type}) => type === notifierChannel.type) will give you the object within the array. you don't need to access it by index.

2021-05-24 08:25 UTC, jurajpiar approved these changes

2021-05-24 08:25 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
>      const newChannels = addedChannels.filter((i) => i.type !== event.currentTarget.id)
```suggestion
  const removeChannel = ({ currentTarget }): void => {
    const newChannels = addedChannels.filter(({ type }) => type !== currentTarget.id)
```

2021-05-24 08:25 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +  const canAddEvent = (): boolean => Boolean(eventData.addedChannels?.length && eventData.event)
since it's this small and it's used only once you may as well add it in the prop directly.

2021-05-24 08:25 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +  // const defaultEvent: string = events.length ? events[0].name : ''
remove comment

2021-05-24 08:25 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                            }
formatting

2021-05-24 08:25 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                        }
formatting

2021-05-24 08:25 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                                }
formatting

2021-05-24 08:25 UTC, jurajpiar commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +                        }
formatting?

2021-05-24 08:25 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +    const newevents = events.filter((i) => i.id !== e.currentTarget.id)
```suggestion
    const newevents = events.filter(({ id }) => id !== e.currentTarget.id)
```

2021-05-24 08:55 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                            }
you are looking at outdated

2021-05-24 08:56 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                        }
you are looking at outdated

2021-05-24 08:56 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +                                }
you are looking at outdated

2021-05-24 08:57 UTC, vjgene commented on src/components/organisms/notifier/NotificationChannelsList.tsx
> +                        }
formatted as per eslint rules. it seems you are referring to outdated

2021-05-24 09:25 UTC, vjgene commented on src/components/organisms/notifier/NotificationChannelsList.tsx
>      const newChannels = addedChannels.filter((i) => i.type !== event.currentTarget.id)
done

2021-05-24 09:25 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +  const canAddEvent = (): boolean => Boolean(eventData.addedChannels?.length && eventData.event)
done

2021-05-24 09:25 UTC, vjgene commented on src/components/organisms/notifier/NotificationEventCreate.tsx
> +  // const defaultEvent: string = events.length ? events[0].name : ''
done

2021-05-24 11:40 UTC, farinalvaro approved these changes
LGTM

2021-05-24 11:53 UTC, merged