feat(notifier): adds view of own purchases
rsksmart/rif-marketplace-ui pull request #851
Opened 2021-05-19 10:17 UTC by jurajpiar

Resolves https://rsklabs.atlassian.net/browse/RMKT-633

2021-05-25 21:26 UTC, farinalvaro requested changes
Why are we updating `package-lock.json` file in this PR?
Apart from that my other suggestions are minor and looks good.

2021-05-25 21:26 UTC, farinalvaro commented on src/components/atoms/CrossBtn.tsx
> +const CrossBtn: FC<Props> = ({ hoverText, ...props }) => (
Can't we use [MaterialUI `ActionButton`](https://material-ui.com/api/icon-button/) component?

2021-05-25 21:26 UTC, farinalvaro commented on src/components/atoms/RoundedCard.tsx
> +import { CardProps } from '@material-ui/core'
This can be added in the above `import Card from '@material-ui/core/Card'`

2021-05-25 21:26 UTC, farinalvaro commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +import { Grid } from '@material-ui/core'
```suggestion
import Grid from '@material-ui/core/Grid'
```

2021-05-25 21:26 UTC, farinalvaro commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +    minHeight: '529px',
Can we use something more dynamic/responsive?

2021-05-25 21:26 UTC, farinalvaro commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +                </MarketplaceCell>
Please, extract into different components if possible

2021-05-25 21:26 UTC, farinalvaro commented on src/utils/tokenUtils.ts
> +export const getFiatPrice = (price: Big, token?: TokenXR) => price.mul(token?.rate || 0).toFixed(2)
Nice one!

2021-05-25 21:26 UTC, farinalvaro commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +      backgroundColor: 'rgba(0, 0, 0, 0.2)',
Can we use a color already defined in our theme instance? If not, please define it somewhere else so it's easier to maintain our palette 🙏

2021-05-25 21:26 UTC, farinalvaro commented on src/assets/images/closingCross.svg
> +</svg>
In case we can't use a MaterialUI icon button component, can we use a MaterialUI Icon instead of adding a new image? [Reference](https://material-ui.com/components/material-icons/)

2021-05-26 08:59 UTC, jurajpiar commented on src/components/atoms/CrossBtn.tsx
> +const CrossBtn: FC<Props> = ({ hoverText, ...props }) => (
Good point

2021-05-26 09:03 UTC, jurajpiar commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +    minHeight: '529px',
Well, it's not likely to get any smaller is it

2021-05-26 09:13 UTC, jurajpiar commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +                </MarketplaceCell>
No man, I've decided against that as it will create unnecessary complexity and wont make things that much clearer as the grid structure would remain in this component. With the section comments it is fairly clear what is where is it not?

2021-05-26 09:15 UTC, jurajpiar commented on src/assets/images/closingCross.svg
> +</svg>
Well, that's not what the design perscribes and we did not discuss alternatives.

2021-05-26 10:38 UTC, jurajpiar commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +      backgroundColor: 'rgba(0, 0, 0, 0.2)',
I moved this into it's own component, which should become the dialog/modal component to use. As such the background colour will only ever be used here so no need to extract it elsewhere. In fact the only place that it would make sense to extract to would be the rifui theme. Should you add it there we can change this one to get it from there. Personally, I don't want to touch rifui as it takes too much time to get a simple thing done from code to usage (for me that is).

2021-05-26 10:40 UTC, jurajpiar commented
> Why are we updating package-lock.json file in this PR?

Why not? Some packages got clearly updated to their newer hotfix versions after running npm i...

2021-05-26 10:58 UTC, vjgene reviewed
Looks good except for one minor change

2021-05-26 10:58 UTC, vjgene commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +  if (planStatus !== 'ACTIVE' || daysLeft <= 0) return 'blocked'
Can we use a constant here instead of string?

2021-05-26 12:53 UTC, farinalvaro commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +                </MarketplaceCell>
Makes sense 👌

2021-05-26 13:02 UTC, farinalvaro commented on src/components/organisms/notifier/mypurchase/NotifierDetailsModal.tsx
> +      backgroundColor: 'rgba(0, 0, 0, 0.2)',
Cool, resolving as discussed 👌

2021-05-26 14:15 UTC, jurajpiar commented on src/assets/images/closingCross.svg
> +</svg>
done

2021-05-26 14:57 UTC, farinalvaro approved these changes
LGTM

2021-05-27 07:00 UTC, merged