feat(notifier): add new block event
rsksmart/rif-marketplace-ui pull request #861
Opened 2021-05-20 14:35 UTC by vjgene

Adds new block event functionality to add events page - RGWY690

2021-05-20 17:47 UTC, farinalvaro reviewed
I'm not sure I understood the goal of this PR. Is it rebased on https://github.com/rsksmart/rif-marketplace-ui/pull/849 and should we merge that one before this one?

2021-05-24 16:15 UTC, jurajpiar requested changes
Good good, just don't use react state to store dom keys.

2021-05-24 16:15 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const [key, setKey] = useState<number>(0)
don't store DOM keys in a state like this.

2021-05-24 16:15 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +        && events.find((addedEvent) => addedEvent.type === SUPPORTED_EVENTS.NEWBLOCK)) {
the repetition of `notifierEvent.type === SUPPORTED_EVENTS.NEWBLOCK` seems to warrant refactor to a function.

2021-05-24 16:15 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +          setKey(key + 1)
delete

2021-05-24 16:15 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +            key={key}
using indexes for keys is discouraged. if you don't have anything that would uniquely identify an event, then convert it to string.

2021-05-24 17:29 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const [key, setKey] = useState<number>(0)
using generator function instead for keys

2021-05-24 17:29 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +        && events.find((addedEvent) => addedEvent.type === SUPPORTED_EVENTS.NEWBLOCK)) {
done

2021-05-24 17:29 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +            key={key}
using generator function

2021-05-24 17:34 UTC, jurajpiar requested changes

2021-05-24 17:34 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const generateKey = (): string => `'eve_'${new Date().getTime()}`
I recommend the following react docs to understand what to use for keys: https://reactjs.org/docs/lists-and-keys.html. The rule of thumb is: use unique and static values for keys.

2021-05-24 18:19 UTC, farinalvaro requested changes
I might be missing something, but I didn't get the use of a `key` prop on a single component, is it supposed to be under some iteration?

2021-05-24 18:19 UTC, farinalvaro commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +            key={generateKey()}
Do we need a key here?

2021-05-24 19:23 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const generateKey = (): string => `'eve_'${new Date().getTime()}`
using key to reinitailize component.. reference here - https://kentcdodds.com/blog/understanding-reacts-key-prop

2021-05-24 19:23 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +            key={generateKey()}
using key to reinitailize component.. reference here - https://kentcdodds.com/blog/understanding-reacts-key-prop

2021-05-24 19:45 UTC, farinalvaro approved these changes

2021-05-24 19:45 UTC, farinalvaro commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +  const generateKey = (): string => `'eve_'${new Date().getTime()}`
```suggestion
  const generateKey = (): string => `eve_${new Date().getTime()}`
```

2021-05-24 19:45 UTC, farinalvaro commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +            key={generateKey()}
Ah ok, I didn't think about using it this way. Thanks for the reference 👍.

2021-05-24 23:13 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx
> +            key={generateKey()}
Well whilst the article is certainly enlightening I personally still don't understand how exactly is your code benefiting from using this reinitialisation. Could you elaborate on that please?

2021-05-25 08:36 UTC, jurajpiar approved these changes
Nice one

2021-05-25 08:51 UTC, merged