feat(notifier): adds checkout buy stepper
rsksmart/rif-marketplace-ui pull request #862
Opened 2021-05-21 13:35 UTC by farinalvaro

2021-05-25 21:06 UTC, itofarina commented on src/components/organisms/notifier/buy/EventsRegistrar.tsx
> +import React, { FC, useState } from 'react'
There's almost nothing new in this file, this was extracted from `src/components/pages/notifier/buy/NotifierOffersSelectedPage.tsx`

2021-05-26 10:41 UTC, vjgene reviewed
Nice work!

2021-05-26 10:41 UTC, vjgene commented on src/components/molecules/ExpirationDate.tsx
> +        {type === 'warning' && <WatchLaterIcon />}
can we use a constant here for ex. type === NOTIFIER_MESSAGES.WARNING?

2021-05-26 13:30 UTC, jurajpiar requested changes
Please remove the price selector and and use the currentFiat from marktetcontext.

2021-05-26 13:30 UTC, jurajpiar commented on src/components/organisms/notifier/buy/CheckoutPayment.tsx
> +          />
The currency choice has been removed from the design by agreement. unfortunately, the designs nor the story has been updated to reflect this change. The reason for this is that the consumer makes the choice on the offers page.

2021-05-26 13:30 UTC, jurajpiar commented on src/components/molecules/PriceSummary.tsx
> +          color="primary.main"
that's rather odd notation. where is this from? I think I'd rather these were defined with JSS.

2021-05-26 13:30 UTC, jurajpiar commented on src/components/organisms/notifier/buy/CheckoutStepper.tsx
> +            fiatUnit={SYSTEM_SUPPORTED_FIAT.usd}
use `exchangeRates.currentFiat` from the market context

2021-05-26 13:30 UTC, jurajpiar commented on src/components/molecules/PriceSummary.tsx
> +  fiatUnit: SYSTEM_SUPPORTED_FIAT
```suggestion
  cryptoPrice: Big
  currency: TokenXR
  fiat: BaseFiat
```

2021-05-26 13:30 UTC, jurajpiar commented on src/components/organisms/notifier/buy/CheckoutPayment.tsx
> +  cryptoXRs: MarketCryptoRecord
```suggestion
  fiat: BaseFiat
  expirationDate: Date
  currency: TokenXR
```

2021-05-26 13:30 UTC, jurajpiar commented on src/components/organisms/notifier/buy/CheckoutPayment.tsx
> +            />
not sure it is that much improvement on:
```suggestion
            <Typography variant="body2" color="textSecondary">
              {getShortDateString(expirationDate)}
            </Typography>
```
considering that the icon is not going to be used here. Seems unnecessarily complicated to just display text.

2021-05-26 19:59 UTC, farinalvaro commented on src/components/molecules/PriceSummary.tsx
> +          color="primary.main"
Resolving as we already discussed this one. [Reference](https://material-ui.com/system/typography/#font-size)

2021-05-26 20:00 UTC, farinalvaro commented on src/components/organisms/notifier/buy/CheckoutPayment.tsx
> +            />
Resolving after our discussion and agreement on reusing an existing component.

2021-05-26 20:00 UTC, farinalvaro commented on src/components/organisms/notifier/buy/CheckoutPayment.tsx
> +          />
That changes a lot the implementation, thank you for this!

2021-05-26 20:46 UTC, farinalvaro commented on src/components/organisms/notifier/buy/CheckoutPayment.tsx
> +          />
Done

2021-05-26 20:46 UTC, farinalvaro commented on src/components/molecules/PriceSummary.tsx
> +  fiatUnit: SYSTEM_SUPPORTED_FIAT
Done, thank you!

2021-05-26 20:47 UTC, farinalvaro commented on src/components/organisms/notifier/buy/CheckoutPayment.tsx
> +  cryptoXRs: MarketCryptoRecord
Done, thank you!

2021-05-26 20:47 UTC, farinalvaro commented on src/components/organisms/notifier/buy/CheckoutStepper.tsx
> +            fiatUnit={SYSTEM_SUPPORTED_FIAT.usd}
Done, thank you!

2021-05-26 20:52 UTC, farinalvaro commented on src/components/molecules/ExpirationDate.tsx
> +        {type === 'warning' && <WatchLaterIcon />}
Hey, thanks for this suggestion!
I thought you were right but after looking closer I realized that `type` variable is typed as `export type SubscriptionExpirationType = 'normal' | 'warning' | 'blocked'`

So it can only be one of those types or the code won't compile.

2021-05-27 07:12 UTC, jurajpiar approved these changes

2021-05-27 13:33 UTC, merged