feat(notifier): adds provider validation
rsksmart/rif-marketplace-ui pull request #866
Opened 2021-05-26 09:59 UTC by vjgene

Adds provider url validation during registration

2021-05-26 15:50 UTC, jurajpiar requested changes, later dismissed
Tiny things though I feel I you might have misunderstood me when I said to just use the existing service for your endpoint.

2021-05-26 15:50 UTC, jurajpiar commented on src/models/UIMessage.ts
> +    MarketErrorId | NotifierErrorId
Remove from here. It's too domain specific for this place.

2021-05-26 15:50 UTC, jurajpiar commented on src/components/organisms/notifier/ProviderRegistrar.tsx
> +        id: 'notifier-provider',
that's just an api error type. the text should be used to narrow down the location of the error.

2021-05-26 15:50 UTC, jurajpiar commented on src/api/rif-notifier-service/provider.ts
> +  }
how come you didn't just add and endpoint to the existing api file?

2021-05-26 16:59 UTC, vjgene commented on src/api/rif-notifier-service/provider.ts
> +  }
This i wanted to separate validation logic from core notification service

2021-05-26 19:32 UTC, jurajpiar approved these changes
LGTM

2021-05-26 19:50 UTC, farinalvaro approved these changes
Apart from the minor `type` comments looks great!

2021-05-26 19:50 UTC, farinalvaro commented on src/components/organisms/notifier/ProviderRegistrar.tsx
> +                    validate: { validateProviderURL },
😍

2021-05-26 19:50 UTC, farinalvaro commented on src/constants/strings.ts
> +}
Could it be better to have it as
`type ApiResponse = 'OK' | 'ERROR'`?

2021-05-26 19:50 UTC, farinalvaro commented on src/components/organisms/notifier/ProviderRegistrar.tsx
> +    const result: string = await notifierService.healthCheck().catch((error) => {
I would prefer to not use string return and use a type instead like:
`result: ApiResponse = ...`

2021-05-27 08:49 UTC, jurajpiar requested changes

2021-05-27 08:49 UTC, jurajpiar commented on src/constants/strings.ts
> +}
either that or better still,
```suggestion
export const API_RESPONSE_STATUS = {
  OK: 'OK',
  ERROR: 'error',
}

export type ApiResponse = keyof typeof API_RESPONSE_STATUS
```

2021-05-27 08:49 UTC, jurajpiar commented on src/components/organisms/notifier/ProviderRegistrar.tsx
> +    const result: string = await notifierService.healthCheck().catch((error) => {
if you are going to do apply this suggestion Vijay, then you might as well do it properly and move the logic part to a mapping.
Also I've just realised that the service is misused a bit. Let's have a call about it.

2021-05-27 12:42 UTC, jurajpiar approved these changes

2021-05-27 13:38 UTC, merged