feat(notifier): adds ability to buy plan
rsksmart/rif-marketplace-ui pull request #870
Opened 2021-05-28 13:38 UTC by farinalvaro

2021-06-08 10:03 UTC, jurajpiar requested changes
There are few things to look at here. Mainly structural really.

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/subscriptionPlan.ts
>  }
remove `& {
        content: Array<SubscriptionPlanDTO>
}` since you are already doing it via generics

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/subscriptionBatch.ts
> +  )
please don't use the node fetch. Instead use the same structure as the rest of the services. For reference you can use the `subscriptionPlan.ts` file.

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/interfaces.ts
> +  status: NotifierResponseStatus
I don't understand this change. The generic is fine but why does the message need to be a string and why is there property `status` all the sudden? It doesn't seem to be used anywhere..

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/response.ts
> +export type NotifierResponseStatus = keyof typeof NOTIFIER_RESPONSE_STATUSES
revert as this is indeed a message

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/interfaces.ts
> +  fetch = (): Promise<NotifierResponse<any>> => this._fetch()
prefer propagating the generic rather than typing to `any`
```suggestion
  fetch = <T>(): Promise<NotifierResponse<T>> => this._fetch()
```

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/subscriptions.ts
> +  filter?: string
why did you make these undefinable? Is there a chance they will not exist in the response? If you need a subset type for sending data then create a new type that picks/omits some params.

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/subscriptions.ts
> +  idTopic?: number
why did you make these undefinable? Is there a chance they will not exist in the response? If you need a subset type for sending data then create a new type that picks/omits some params.

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/subscriptions.ts
> +  topicParams?: Array<TopicParams>
why did you make these undefinable? Is there a chance they will not exist in the response? If you need a subset type for sending data then create a new type that picks/omits some params.

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/subscriptions.ts
> +export type SubscribeToPlanDTO = {
I'd change all `SubscribeToPlan...` to `NewSubscription...`

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/subscriptions.ts
> +}
doesn't seem to be used anywhere. Also replicating existing code (in `models/Token.ts`).

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-notifier-service/models/subscriptions.ts
> +}
Also the capitalised currency name in the notifier service is just an example and we should in fact start using the non-capitalised symbol that we use everywhere else.

2021-06-08 10:03 UTC, jurajpiar commented on src/api/rif-marketplace-cache/notifier/offers/models.ts
>    id: number
let's omit the `id` from the response as it doesn't represent anything useful. 
Then  make the `NotifierPlan = Item & ...` where the `NotifierPlan.id = planId` in the mapping. This will also render the `NotifierOfferItem` redundant, so you can either remove it or make it `NotifierOfferItem = NotifierPlan`.

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +
Use `channels.map`

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +    } else if (eventType === SUPPORTED_EVENTS.SMARTCONTRACT) {
what happens when we add another event type (there are currently 3 types in the notifier svc)? might be cleaner to create a mapping rather than if else

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +          topicParams.push(topicParam)
5 block levels in... can this be refactored?

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +            valueType: valueType.charAt(0).toUpperCase() + valueType.slice(1),
why does this need to be capitalised?

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +const buildSubscribeToPlanDTO = (
could you make a test for this function please? Will make it easier to refactor.

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +  const handleEventItemRemoved = (
```suggestion
  const handleOnEventRemoved = (
```

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +  const handleEventItemAdded = (
```suggestion
  const handleOnEventAdded = (
```

2021-06-08 10:03 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +    if (!account) return // should be unreachable if no account is provided
no need for the comment.

2021-06-08 10:03 UTC, jurajpiar commented on src/context/Confirmations/interfaces.ts
> +type NotifierContractAction = 'NOTIFIER_REGISTER_PROVIDER' | 'NOTIFIER_WITHDRAW_FUNDS' | 'NOTIFIER_CREATE_SUBSCRIPTION'
Created an issue to refactor this file: https://rsklabs.atlassian.net/browse/RMKT-768. This is just to note it.

2021-06-08 10:03 UTC, jurajpiar commented on src/contracts/notifier/Notifier.ts
> +    },
extract type

2021-06-08 10:03 UTC, jurajpiar commented on src/contracts/notifier/Notifier.ts
> +    } = data
you can do this in the signature, like:
```
public createSubscription = ({
      providerAddress,
      subscriptionHash,
      signature,
      amount,
      token: { tokenAddress },
    }: CreateSubscriptionData,
    txOptions: TxOptions,
) ...
```

2021-06-08 10:03 UTC, jurajpiar commented on src/contracts/notifier/Notifier.ts
> +      signature,
could potentially reduce these 3 to rest.

2021-06-08 10:03 UTC, jurajpiar commented on src/models/marketItems/NotifierEventItem.ts
> +}
these types are purely for displaying. If you need a model that is the same sig as the headers, then create a new one and base the headers upon that if applicable. But put these back to the component they are used in please.

2021-06-08 13:35 UTC, vjgene commented on src/api/rif-notifier-service/interfaces.ts
> +  status: NotifierResponseStatus
Actually status is the one that should be used. The message could be any however status is either 'OK' or 'CONFLICT'. so, it is status that should be used all the times for checking of response status. This response status is not the same as http response status.

2021-06-08 13:36 UTC, vjgene commented on src/api/rif-notifier-service/models/response.ts
> +export type NotifierResponseStatus = keyof typeof NOTIFIER_RESPONSE_STATUSES
> revert as this is indeed a message

We need to use NotifierResponseStatus for checks. Not message.

2021-06-08 15:16 UTC, vjgene commented on src/api/rif-notifier-service/models/subscriptions.ts
> +  filter?: string
removing unwanted fields

2021-06-08 16:57 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +            valueType: valueType.charAt(0).toUpperCase() + valueType.slice(1),
> why does this need to be capitalised?

the input type (for ex. uint256 to be represented as Uint256 in java and notifier web3 version)

2021-06-09 09:00 UTC, vjgene commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +  const handleEventItemAdded = (
> 

we cannot use handle and on together. Conventionally it's either on.... or handle..

so,  it should be handleEventAdded?

2021-06-09 10:31 UTC, vjgene commented on src/contracts/notifier/Notifier.ts
> +      signature,
> could potentially reduce these 3 to rest.

what does it mean? these parameters are to be sent as first 3 parameters

2021-06-10 10:49 UTC, jurajpiar approved these changes

2021-06-10 10:49 UTC, jurajpiar commented on src/api/rif-marketplace-cache/notifier/offers/api.ts
> +  planId,
Do we need both of these fields? Or could we just do with the first one?

2021-06-10 10:49 UTC, jurajpiar commented on src/api/models/restAPIService.ts
> +    abstract _create: <T, S>(data: T, params?: S) => Promise<any>
Strange mix of generics and any. Perhaps make the response generic too then?

2021-06-10 10:49 UTC, jurajpiar commented on src/api/rif-notifier-service/subscriptionBatch.ts
> +    })
Please do fix the line length in your code.

2021-06-10 10:49 UTC, jurajpiar commented on src/api/rif-notifier-service/subscriptionBatch.ts
> +  }
Why using generics here if you know the types?
```suggestion
   subscribeToPlan = (
    subscriptionData: SubscribeToPlanDTO,
  ): Promise<SubscribeToPlanResponseDTO> => this.create(subscriptionData)
    .catch((error) => {
      this.errorReporter({
        error: new Error(error),
        text: 'Error Creating new subscription',
        id: 'service-fetch',
      })
    })
```

2021-06-10 10:49 UTC, jurajpiar commented on src/api/rif-notifier-service/subscriptionBatch.ts
> +  }
```suggestion
   _create = async <T>(
    subscriptionData: T,
  ): Promise<SubscribeToPlanResponseDTO> => {
    const { content }: SubscribeToPlanResponse = await this.service
      .create(subscriptionData)
    return content
  }
```

2021-06-10 10:49 UTC, jurajpiar commented on src/api/rif-notifier-service/subscriptionBatch.ts
> +export default class SubscribeToPlanService
```suggestion
export const address = 'subscribeToPlan' as const
type SubscribeToPlanResponse = NotifierResponse<SubscribeToPlanResponseDTO>

export default class SubscribeToPlanService
```

to go with the change to `_create`

2021-06-10 10:49 UTC, jurajpiar commented on src/api/rif-notifier-service/subscriptionPlans.ts
> +  }
Why returning true, or in fact why type it so arbitrarily? Maybe just
```suggestion
  _create = <T>(data: T): Promise<unknown> => this.service.create(data)
```
would do? Or, since this endpoint never uses it even:
```suggestion
  _create!: <T, S>(data: T, params?: S | undefined) => Promise<any>
```
would suffice. Or, cleaner still:
```suggestion
  _create = (): Promise<void> => Promise.resolve(logNotImplemented('Subscription Plans')())
```

2021-06-10 10:49 UTC, jurajpiar commented on src/components/pages/notifier/buy/NotifierOfferCheckoutPage.tsx
> +  const handleEventItemAdded = (
sure

2021-06-10 13:21 UTC, vjgene commented on src/api/rif-marketplace-cache/notifier/offers/api.ts
> +  planId,
we need both as planId is the actual id used during purchase, and id could represent cache id of the plan, just not in this case.

2021-06-10 13:31 UTC, merged