feat(notifier) edit provider
rsksmart/rif-marketplace-ui pull request #872
Opened 2021-06-02 13:54 UTC by vjgene

Adds ability to edit a given provider after a warning message

2021-06-03 19:34 UTC, farinalvaro requested changes
The idea looks good, I just think some things could be done simpler 😄. 
I'm happy to have a chat about that

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +        ) }
I think it could be cleaner to have all the `RifDialog`  instance and its content defined outside of the return method or in a separated component, as it changes a lot what's being rendered.  What do you think?

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +const ProviderEdit: FC<Props> = ({ mode }) => {
```suggestion
const ProviderEdition: FC<Props> = ({ mode }) => {
```
or 
```suggestion
const ProviderCreation: FC<Props> = ({ mode }) => {
```

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +}
If there are only 2 modes may be we could directly use a boolean prop like `editMode` so that we don't have to be comparing every time

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +        text: 'Could not register as a provider',
When in edit mode this text should be `Could not edit...` right?

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +        text="Awaiting confirmations for new offer"
```suggestion
        text="Awaiting confirmations for provider registration"
```

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +      </Typography>
I think it could be better to define those strings outside like 
```const title = editMode? 'Edit...' : 'Register...'```

and just render `{title}` directly here.

Same for subtitle

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +        )}
Is it possible to check for edit mode inside the functions and act based on that when needed instead of conditionally rendering here? I would suggest to try that because the render is almost the same.

For example:
```

const buttonLabel = editMode?? "Edit offer"
...
return ...

          <ProviderRegistrar
            providerAddress={accountStr}
            isEnabled={isWhitelistedProvider}
            onRegister={({ endpointUrl }): void => {
              setShowConfirmProviderEdit(true)
              setProviderUrl(endpointUrl)
            }}
            buttonLabel={buttonLabel}
          />
```

2021-06-03 19:34 UTC, farinalvaro commented on src/components/organisms/notifier/offers/ProviderEdit.tsx
> +        doneMsg="You have been registered as a provider!"
When on edit mode:

```suggestion
        title="Editing your provider info!"
        doneMsg="Your provider info has been updated!"
```

2021-06-03 19:34 UTC, farinalvaro commented on src/components/pages/notifier/myoffers/NotifierMyOffersPage.tsx
> +  const handleEditProfile = editProvider
I think we could do this directly here
```suggestion
  const handleEditProfile = ():void => {
    history.push(ROUTES.NOTIFIER.MYOFFERS.EDIT)
  }
```

2021-06-03 19:34 UTC, farinalvaro commented on src/components/pages/notifier/sell/NotifierSellPage.tsx
> +const NotifierSellPage: FC = () => <ProviderEdit mode="CREATE" />
If this is the only thing we would do here I would suggest to remove this file 😄

2021-06-03 19:34 UTC, farinalvaro commented on src/components/pages/notifier/myoffers/NotifierEditOffersPage.tsx
> +const NotifierEditOffersPage: FC = () => <ProviderEdit mode="EDIT" />
May be remove this file if this is the only thing we need

2021-06-08 10:53 UTC, jurajpiar requested changes
Getting there. Please consider and let me know what you think about my suggestions.

2021-06-08 10:53 UTC, jurajpiar commented on src/components/pages/notifier/NotifierRoutes.tsx
> +        })
Use the `WithLoginCard` on the page, not in the router. Just make 2 routes here: one going to `NotifierSellPage` the other `ProviderEditPage` if you need to route to it.

2021-06-08 10:53 UTC, jurajpiar commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +      </RifDialog>
extract component.

2021-06-08 10:53 UTC, jurajpiar commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +const EditProvider: FC<Props> = ({
Actually I think it would be best to just compose a dialog for the entire thing from the `myOffers` page and show the warning as a persistent element within the dialog. That way you don't need to touch the router, or to do conditional page composition. just render the warning with the form bellow it in a modal.

2021-06-08 10:53 UTC, jurajpiar commented on src/components/pages/notifier/provider/ManageProviderPage.tsx
> +                    onClick={
this is not good. consider my above comment to use dialog instead. Alternatively just use 2 different paths in the router. don't conditionally compose the entirety of a page.

2021-06-08 12:29 UTC, vjgene commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +const EditProvider: FC<Props> = ({
Already myoffers page is too long, so we don't want to add more code. Also it's more clear to separate the functionality into EditProvider and AddProvider components since that's their function.

2021-06-08 12:30 UTC, vjgene commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +const EditProvider: FC<Props> = ({
Already myoffers page is too long, so we don't want to add more code. Also it's more clear to separate the functionality into EditProvider and AddProvider components since that's their function.

2021-06-08 12:32 UTC, vjgene commented on src/components/pages/notifier/NotifierRoutes.tsx
> +        })
> Use the `WithLoginCard` on the page, not in the router. Just make 2 routes here: one going to `NotifierSellPage` the other `ProviderEditPage` if you need to route to it.

This will result in two small pages which don't do much, which @farinalvaro doesn't agree with.

2021-06-08 12:34 UTC, vjgene commented on src/components/pages/notifier/provider/ManageProviderPage.tsx
> +                    onClick={
> this is not good. consider my above comment to use dialog instead. Alternatively just use 2 different paths in the router. don't conditionally compose the entirety of a page.

To avoid conditional, we can pass the components as children. But this will result in two pages which almost don't do much. Even react docs support conditional rendering https://reactjs.org/docs/conditional-rendering.html
also long as there are not too many conditions i suppose.

2021-06-08 12:42 UTC, vjgene commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +      </RifDialog>
> extract component.

I think it's good idea. may be we can call it WarningDialog which takes some params. If we see a reusability

2021-06-08 13:58 UTC, jurajpiar commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +const EditProvider: FC<Props> = ({
the more code would be effectively a single line, like `<EditProviderUrlDialog open={isChangingUrl}>`.

2021-06-09 20:00 UTC, farinalvaro commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +      </RifDialog>
Resolving as it's not going to be reused for now

2021-06-09 20:00 UTC, farinalvaro commented on src/components/organisms/notifier/provider/EditProvider.tsx
> +const EditProvider: FC<Props> = ({
Resolving due to change on structure

2021-06-09 20:01 UTC, farinalvaro approved these changes
LGTM - team work 😃

2021-06-10 09:35 UTC, vjgene commented on src/components/organisms/notifier/provider/ProviderEdition.tsx
> +    : 'Registering as a provider!'
How about if we do this?

```
type labelTypes = 'BUTTON_LABEL' | 'INPROGRESS_MESSAGE' | 'DONE_MESSAGE'
const editLabels: Record<labelTypes, string > = {
  BUTTON_LABEL: 'Edit Offer',
  INPROGRESS_MESSAGE: 'Editing your provider info!',
  DONE_MESSAGE: 'Your provider info has been updated!',
}
const createLabels: Record<labelTypes, string> = {
  BUTTON_LABEL: 'Register Provider',
  INPROGRESS_MESSAGE: 'Registering as a provider!',
  DONE_MESSAGE: 'You have been registered as a provider!',
}

```
and then

```
const labels = editMode ? editLabels : createLabels
const buttonLabel = labels.BUTTON_LABEL
const txDoneMsg = labels.DONE_MESSAGE
const txInProgressTitle = labels.INPROGRESS_MESSAGE
```

2021-06-10 09:36 UTC, vjgene reviewed
Looking good. I just think we can use editMode === true once to get all the labels

2021-06-10 10:52 UTC, jurajpiar approved these changes

2021-06-10 12:51 UTC, farinalvaro commented on src/components/organisms/notifier/provider/ProviderEdition.tsx
> +    : 'Registering as a provider!'
Done, thanks

2021-06-10 13:00 UTC, merged