feat(notifier): adds staking service for communication with cache
rsksmart/rif-marketplace-ui pull request #873
Opened 2021-06-02 18:25 UTC by farinalvaro

2021-06-08 08:42 UTC, vjgene approved these changes
Nice work!

2021-06-08 13:56 UTC, jurajpiar requested changes
Nice, I'd just create a single useContext and parametrise the apiAddress.

2021-06-08 13:56 UTC, jurajpiar commented on src/api/rif-marketplace-cache/common/stakes.ts
> +  acc[symbol] = parseToBigDecimal(total, 18).toString()
18 is a default value of decimals so can be omitted

2021-06-08 13:56 UTC, jurajpiar commented on src/context/Services/staking/Context.tsx
> +  if (api && !api.service) {
```suggestion
  if (!api?.service) {
```

2021-06-08 13:56 UTC, jurajpiar commented on src/context/Services/storage/staking/withContext.tsx
> +  )
this could be common no if you parametrise the apiAddress. Kinda makes it worthwhile using a withContext, no?

2021-06-09 20:18 UTC, farinalvaro commented on src/context/Services/storage/staking/withContext.tsx
> +  )
Done, thanks

2021-06-09 20:40 UTC, farinalvaro commented on src/context/Services/staking/Context.tsx
> +  if (api && !api.service) {
To enter this statement we need `api` to be defined but the service not. With this change we always enter this statement and causes an error `"cannot read property connect of undefined"`

2021-06-10 10:50 UTC, jurajpiar approved these changes
LG

2021-06-10 12:49 UTC, merged