feat(notifier): avoids multiple offers creation per provider
rsksmart/rif-marketplace-ui pull request #874
Opened 2021-06-04 20:37 UTC by farinalvaro

…add validation

2021-06-08 08:03 UTC, vjgene requested changes
Looks good overall. I just think it'd be more clear from provider perspective  to add an extra message when provider tries to register using same url again for clarity.

2021-06-08 08:03 UTC, vjgene commented on src/components/pages/notifier/sell/PageWrapper.tsx
> +  if (hasOffer) {
Can we make another condition that if provider tries to register the same url that it shows a message you are already registered as a provider ?

2021-06-08 08:03 UTC, vjgene commented on src/api/rif-marketplace-cache/notifier/offers/__tests__/api.test.ts
>          .map(mapFromTransport)
can we use a better name than mapFromTransport? this seems to be used in multiple places.

2021-06-08 08:03 UTC, vjgene commented on src/api/rif-marketplace-cache/notifier/offers/api.ts
> +      channels: channels ? Array.from(channels) : undefined,
why is undefined being used. if it's an array can we not use []?

2021-06-08 13:22 UTC, farinalvaro commented
@vjgene thanks for reviewing. This PR is still a work in progress as it's a draft 🙂

2021-06-10 19:59 UTC, farinalvaro commented on src/api/rif-marketplace-cache/notifier/offers/api.ts
> +      channels: channels ? Array.from(channels) : undefined,
I think we should be able to only specify the needed filters. Like it's better to not specify the currency if you don't want to filter by currency. Does it make sense?

2021-06-10 20:01 UTC, farinalvaro commented on src/api/rif-marketplace-cache/notifier/offers/__tests__/api.test.ts
>          .map(mapFromTransport)
I think this is not related to this PR. Personally, I like this name like it's a standard to parse the DTOs. We can discuss about changing it of course but don't think this PR is the best place to do it 😄.

2021-06-10 20:03 UTC, farinalvaro commented on src/components/pages/notifier/sell/PageWrapper.tsx
> +  if (hasOffer) {
Actually, if the provider already has an offer we don't show the form, so they won't be able to enter a url.

2021-06-11 15:11 UTC, jurajpiar requested changes

2021-06-11 15:11 UTC, jurajpiar commented on src/components/organisms/storage/sell/NoMultipleOffersCard.tsx
> +const NoMultipleOffersCard: FC<Props> = ({ service }) => {
Take it out of the storage folder if it is meant to be reused outside of storage.
Also, it seems rather hacky. Maybe would be better to take path as argument pass route to it directly?

2021-06-11 15:11 UTC, jurajpiar commented on src/components/pages/notifier/sell/NotifierSellPage.tsx
> +      setHasOffer(Boolean(currentOwnOffers[0]))
Might be safer for runtime to do:
```suggestion
      setHasOffer(Boolean(currentOwnOffers?.length))
```

2021-06-11 15:11 UTC, jurajpiar commented on src/models/marketItems/NotifierFilters.ts
> +    channels?: Set<string>
Let me fix the type of the api's _fetch sig, but I think we should keep these enforced as they serve the purpose (probably) and instead type cast upon use.

2021-06-11 16:06 UTC, jurajpiar approved these changes

2021-06-11 19:25 UTC, farinalvaro commented on src/components/organisms/storage/sell/NoMultipleOffersCard.tsx
> +const NoMultipleOffersCard: FC<Props> = ({ service }) => {
Moved, thanks

2021-06-14 13:02 UTC, vjgene commented on src/components/pages/notifier/sell/NotifierSellPage.tsx
> +      } as NotifierOffersFilters)
What happens if it is the same url but a different provider account? should we also block registration if the url is already registered?

2021-06-14 13:12 UTC, vjgene approved these changes
Everything looks good. Just left a note on registering with same url.

2021-06-14 13:18 UTC, farinalvaro commented on src/components/pages/notifier/sell/NotifierSellPage.tsx
> +      } as NotifierOffersFilters)
Thanks, that's a good point! I might be missing something but why you wouldn't be able to provide the same service with another account?
At least in the SC, the only check is against the account ([reference](https://github.com/rsksmart/rif-marketplace-notifier/blob/master/contracts/NotifierManager.sol#L153))
May be @artem-brazhnikov could help us define this behavior?

2021-06-15 12:24 UTC, farinalvaro commented on src/components/pages/notifier/sell/NotifierSellPage.tsx
> +      } as NotifierOffersFilters)
Resolving as it will be tackled on a separated story

2021-06-15 12:25 UTC, merged