feat(notifier): shows purchases status
rsksmart/rif-marketplace-ui pull request #896
Opened 2021-07-05 17:53 UTC by farinalvaro

2021-07-06 07:52 UTC, artem-brazhnikov approved these changes
lgtm, thanks @farinalvaro

2021-07-06 07:54 UTC, vjgene commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +const CANT_RENEW_MESSAGE = 'Subscriptions renewal is available only for completed or expired purchases'
Can we call it RENEWAL_ERROR_MESSAGE or RENEWAL_BLOCKED_MESSAGE?

2021-07-06 08:16 UTC, vjgene commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +
Instead of still showing the renew button, can we jus hide the renew button and only show the message? 

Also can this renew check for subscriptionService.getActiveSubscriptionForUser() and also hide the renewal button, in case there is active subscription? Otherwise the user will try to renew, and upon attempting the message will be shown.

2021-07-06 08:18 UTC, vjgene requested changes
Looks good. I think it would be better to do an additional check and also change the way we display renew button

2021-07-06 13:13 UTC, farinalvaro commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +const CANT_RENEW_MESSAGE = 'Subscriptions renewal is available only for completed or expired purchases'
This message was taken from [the ticket](https://rsklabs.atlassian.net/jira/software/projects/RMKT/boards/60?selectedIssue=RMKT-796).
Also I don't think it's an error, it's a message on top of a disabled button explaining why it's disabled.

2021-07-06 13:31 UTC, farinalvaro commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +
How do we let the users know why they can't renew if we hide the option? I think a disabled button with a tooltip message is better in terms of UX.
About having an active subscription, we don't need to call the service again, as here we are fetching from notifier service all subscriptions with status !== PENDING.

If I understood correctly, the other suggestion is to disable all renew buttons from a certain provider if there is one active subscription from that provider, right? I think it's a good one.

2021-07-06 15:09 UTC, farinalvaro commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +
So after discussing with Artem we created a [new issue](https://rsklabs.atlassian.net/browse/RMKT-817) for this one.

2021-07-07 07:15 UTC, vjgene commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +
About the second point you are right, we need to disable renewal if there are any active subscriptions for the user for a given provider.

2021-07-07 07:15 UTC, vjgene approved these changes

2021-07-07 12:02 UTC, merged