fix(notifier): uses subscription expiration instead of plan expiration
rsksmart/rif-marketplace-ui pull request #897
Opened 2021-07-06 09:21 UTC by vjgene

https://rsklabs.atlassian.net/jira/software/projects/RMKT/boards/60?selectedIssue=RMKT-798

https://user-images.githubusercontent.com/11134695/124575825-03f1ef80-de4c-11eb-8717-fcbd1a85707c.mp4

2021-07-06 14:09 UTC, jurajpiar requested changes, later dismissed
let's check with @artem-brazhnikov about the ux

2021-07-06 14:09 UTC, jurajpiar commented on src/components/molecules/ExpirationDate.tsx
> +    color: palette.error.main,
I think it has been agreed to ditch the red colouring in favour of disabling it, unless that requirement had changed recently. @artem-brazhnikov could you confirm either way, please?

2021-07-06 15:29 UTC, artem-brazhnikov commented on src/components/molecules/ExpirationDate.tsx
> +    color: palette.error.main,
@jurajpiar it should be disabled and grey if the plan was deleted. and red if expired

2021-07-06 15:31 UTC, farinalvaro commented on src/components/pages/notifier/mypurchase/mapMyPurchases.tsx
> +  const daysLeft = Math.ceil(Math.abs(new Date().getTime() - expirationDate?.getTime()) / 86400000)
```suggestion
  const daysLeft = Math.ceil(Math.abs(new Date().getTime() - expirationDate?.getTime()) / 60*60*24*1000)
```

Or create a util function `timestampToDays(milliseconds)`

2021-07-07 12:43 UTC, farinalvaro approved these changes

2021-07-07 15:24 UTC, merged