feat(notifier): shows latest own subs only
rsksmart/rif-marketplace-ui pull request #908
Opened 2021-07-14 09:01 UTC by jurajpiar

Resolves https://rsklabs.atlassian.net/browse/RMKT-793

by adding a filter to the incoming subscriptions.

## Notes:
- As mentioned in the code, this is not ideal, as we make the browser work on something that could be done by the cache database (upon a query from the UI).
> This should really be done in SQL (cache) but sequelize doesn't support subquery and raw query would be impractical in this case (src: https://github.com/sequelize/sequelize/issues/5354)
- I cheated slightly and used the expiry date to filter in the correct subscription. This is based on the assumption that a renewed subscription will always have a later date than an expired one. This in turn is based on the limitation of the notifier, where the renewal is not possible for "completed" subscriptions, i.e. those that ran out of notifications before expiring. Otherwise, it would have to differentiate on the status, which would make it more complex.

## Screens:
**Before:**
![Screenshot 2021-07-14 at 09 35 02](https://user-images.githubusercontent.com/36888576/125593149-8b871c1c-bdb1-4eb1-b197-2d26f08d275d.png)
**After when got only expired:**
![Screenshot 2021-07-14 at 09 43 58](https://user-images.githubusercontent.com/36888576/125593142-f6d6e978-7394-4097-9c0e-fe3562fb4e1a.png)
**After when got expired and renewed:**
![Screenshot 2021-07-14 at 09 37 49](https://user-images.githubusercontent.com/36888576/125593147-7950e979-7927-49c4-a338-cf1d11276287.png)

2021-07-14 15:16 UTC, artem-brazhnikov approved these changes

2021-07-14 15:16 UTC, artem-brazhnikov commented on src/components/pages/notifier/mypurchase/NotifierMyPurchasePage.tsx
> +              ? cur : sub
I would re-write it so it's more readable. but it's not crucial for me now as soon as it works correctly.

2021-07-14 15:41 UTC, jurajpiar commented on src/components/pages/notifier/mypurchase/NotifierMyPurchasePage.tsx
> +              ? cur : sub
done

2021-07-14 15:52 UTC, farinalvaro reviewed
LGTM

2021-07-14 15:53 UTC, farinalvaro approved these changes
LGTM

2021-07-15 10:09 UTC, vjgene requested changes

2021-07-15 10:09 UTC, vjgene commented on src/components/pages/notifier/mypurchase/NotifierMyPurchasePage.tsx
> +            acc[planId] = successor ?? subscription
when we add multiple active subscriptions per plan, grouping by planid will have issues. what if we just display those subscriptions with previousSubscription is null?

2021-07-15 11:28 UTC, vjgene commented on src/components/pages/notifier/mypurchase/NotifierMyPurchasePage.tsx
> +          setSubscriptions(Object.values(filtered))
const filtered = incomingSubscriptions.reduce((acc, subscription) => {
              const { id } = subscription
              const successor = incomingSubscriptions.find(
                ({ prevId }) => id === prevId ,
              )
              const sub = successor ? successor : subscription
              acc.indexOf(sub) === -1 && acc.push(successor ? successor : subscription)
              return acc
            }, [])
setSubscriptions(filtered)

2021-07-19 08:37 UTC, jurajpiar commented on src/components/pages/notifier/mypurchase/NotifierMyPurchasePage.tsx
> +            acc[planId] = successor ?? subscription
Thought, we're not going to implement multiple active subscriptions per plan.
OK, I'll change that.

2021-07-19 09:03 UTC, jurajpiar commented on src/components/pages/notifier/mypurchase/NotifierMyPurchasePage.tsx
> +          setSubscriptions(Object.values(filtered))
Thanks for the suggestion. Minor comments: 
1. mutating arrays (acc.push)
2. ~acc.indexOf(sub) === -1~ acc.includes(sub)
3. if (acc.indexOf(sub) === -1) acc.push(sub), this will not work for subs renewed more than once, if I'm not mistaken

2021-07-19 09:42 UTC, vjgene commented on src/components/pages/notifier/mypurchase/NotifierMyPurchasePage.tsx
> +          setSubscriptions(Object.values(filtered))
For point 2 it's also an option to use "const initial: Set<NotifierSubscriptionItem> = new Set<NotifierSubscriptionItem>()
then initial.add(sub)
For point 3. you can only renew a subscription, only once. once renewed that subscription will be hidden, since previousSubscription is shown instead of the original

2021-07-19 12:10 UTC, jurajpiar commented
Waiting for decision https://rsklabs.atlassian.net/browse/RMKT-793

2021-07-19 12:43 UTC, jurajpiar commented
Closing in favour of a new solution (<PR_LINK>)

2021-07-19 12:43 UTC, closed without merging